import type { FormQuestion } from "./questions.js";

const NSO_EN = ["Never", "Sometimes", "Often"];
const NSO_ZH = ["从不", "有时", "经常"];

const q = (id: string, en: string, zh: string): FormQuestion => ({
  id, text: en, textChinese: zh, textKorean: "",
  type: "likert", options: NSO_EN, optionsChinese: NSO_ZH, optionsKorean: [],
  domain: "executive-function", required: true,
});

// ─── BRIEF-2 Parent Form (63 items) ───────────────────────────────────────────

export const BRIEF2_PARENT_FORM: FormQuestion[] = [
  q("b2p-1",  "Is fidgety",                                                                                                                         "烦躁不安"),
  q("b2p-2",  "Resists or has trouble accepting a different way to solve a problem with schoolwork, friends, tasks, etc.",                            "抵制或在解决学校作业、朋友、任务等方面的问题时有困难接受不同的解决方式"),
  q("b2p-3",  "When given three things to do, remembers only the first or last",                                                                     "在给定三件事情要做时，只记得第一件或最后一件"),
  q("b2p-4",  "Is unaware of how his/her behavior affects or bothers others",                                                                        "不知道自己的行为如何影响或打扰他人"),
  q("b2p-5",  "Work is sloppy",                                                                                                                      "工作草率"),
  q("b2p-6",  "Has explosive, angry outbursts",                                                                                                      "爆炸性、愤怒的发作"),
  q("b2p-7",  "Does not plan ahead for school assignments",                                                                                          "不提前计划学校作业"),
  q("b2p-8",  "Cannot find things in desk",                                                                                                          "在书桌上找不到东西"),
  q("b2p-9",  "Is not a self-starter",                                                                                                               "不是自我启动者"),
  q("b2p-10", "Does not think before doing (is impulsive)",                                                                                          "做事不先考虑（冲动）"),
  q("b2p-11", "Has trouble getting used to new situations (classes, groups, friends, etc.)",                                                          "在适应新环境（课程、团体、朋友等）时遇到困难"),
  q("b2p-12", "Has a short attention span",                                                                                                          "注意力不集中"),
  q("b2p-13", "Has poor understanding of own strengths and weaknesses",                                                                              "对自身的优点和缺点了解不清楚"),
  q("b2p-14", "Has outbursts for little reason",                                                                                                     "缘由微末事发脾气"),
  q("b2p-15", "Gets caught up in details and misses the big picture",                                                                                "陷入细节中，忽略大局"),
  q("b2p-16", "Gets out of control more than friends",                                                                                               "比朋友更容易失控"),
  q("b2p-17", "Gets stuck on one topic or activity",                                                                                                 "容易被一个话题或活动困住"),
  q("b2p-18", "Forgets his/her name",                                                                                                                "忘记自己的名字"),
  q("b2p-19", "Has trouble with tasks that have more than one step",                                                                                  "难以完成多步骤任务"),
  q("b2p-20", "Does not realize that certain actions bother others",                                                                                  "没意识到自己的某些行为会打扰他人"),
  q("b2p-21", "Written work is poorly organized",                                                                                                    "书面工作组织混乱"),
  q("b2p-22", "Small events trigger big reactions",                                                                                                   "小事引发大反应"),
  q("b2p-23", "Has good ideas but does not get job done (lacks follow-through)",                                                                     "拥有好主意但无法完成任务（缺乏执行力）"),
  q("b2p-24", "Talks at the wrong time",                                                                                                             "错过说话时机"),
  q("b2p-25", "Has trouble finishing tasks (assignments, homework, etc.)",                                                                            "完成任务困难（作业、功课等）"),
  q("b2p-26", "Does not notice when his/her behavior causes negative reactions",                                                                     "注意不到自己的行为引起了负面反应"),
  q("b2p-27", "Reacts more strongly to situations than other children",                                                                              "对情况的反应比其他孩子更强烈"),
  q("b2p-28", "Has trouble remembering things, even for a few minutes",                                                                              "记忆中的事情困难，甚至只有几分钟"),
  q("b2p-29", "Makes careless errors",                                                                                                               "粗心造成错误"),
  q("b2p-30", "Gets out of seat at the wrong times",                                                                                                 "错误时起立"),
  q("b2p-31", "Becomes upset with new situations",                                                                                                   "对新情况感到困扰"),
  q("b2p-32", "Has trouble concentrating on schoolwork, etc.",                                                                                       "难以集中精力完成学业等任务"),
  q("b2p-33", "Has poor handwriting",                                                                                                                "笔迹潦草"),
  q("b2p-34", "Mood changes frequently",                                                                                                             "心情经常变化"),
  q("b2p-35", "Has good ideas but cannot get them on paper",                                                                                         "有好点子但无法写下来"),
  q("b2p-36", "Has trouble counting to three",                                                                                                       "数到三有困难"),
  q("b2p-37", "Leaves messes that others have to clean up",                                                                                          "留下别人必须打扫的混乱"),
  q("b2p-38", "Needs to be told to begin a task even when willing",                                                                                  "即使愿意也需要被告知开始任务"),
  q("b2p-39", "Acts too wild or \"out of control\"",                                                                                                 "行为过于狂野或\"失控\""),
  q("b2p-40", "Thinks too much about the same topic",                                                                                                "过度考虑同一个话题"),
  q("b2p-41", "Forgets what he/she was doing",                                                                                                       "忘记自己正在做什么"),
  q("b2p-42", "Does not check work for mistakes",                                                                                                    "不检查工作中的错误"),
  q("b2p-43", "Angry or tearful outbursts are intense but end suddenly",                                                                             "愤怒或哭泣的发作激烈但突然结束"),
  q("b2p-44", "Becomes overwhelmed by large assignments",                                                                                            "大型任务使之无法承受"),
  q("b2p-45", "Loses lunch box, lunch money, permission slips, homework, etc.",                                                                      "丢失午餐盒、午餐钱、许可证、家庭作业等"),
  q("b2p-46", "Needs help from an adult to stay on task",                                                                                            "需要成人帮助保持专注"),
  q("b2p-47", "Forgets to hand in homework, even when completed",                                                                                    "即使完成，也会忘记交作业"),
  q("b2p-48", "Has trouble putting the brakes on his/her actions",                                                                                   "难以控制自己的行为"),
  q("b2p-49", "Resists change of routine, foods, places, etc.",                                                                                      "抵制日常变化、食物、地点等"),
  q("b2p-50", "Has trouble getting started on work",                                                                                                 "很难开始工作"),
  q("b2p-51", "Mood is easily influenced by the situation",                                                                                          "心情很容易受环境影响"),
  q("b2p-52", "Underestimates time needed to finish tasks",                                                                                          "低估完成任务所需的时间"),
  q("b2p-53", "Does not bring home homework, assignment sheets, materials, etc.",                                                                     "不带回家作业、作业单、材料等"),
  q("b2p-54", "Cannot find the front door of home",                                                                                                  "找不到家的前门"),
  q("b2p-55", "Does not take initiative",                                                                                                            "不主动"),
  q("b2p-56", "Becomes upset too easily",                                                                                                            "很容易心烦意乱"),
  q("b2p-57", "Starts assignments at the last minute",                                                                                               "在最后一刻开始任务"),
  q("b2p-58", "Has trouble moving from one activity to another",                                                                                     "在从一项活动转移到另一项活动时遇到困难"),
  q("b2p-59", "Has trouble carrying out the actions needed to reach goals (saving money for special item, studying to get a good grade, etc.)",       "在执行达成目标所需的行动时遇到困难（例如为特别物品储蓄，为了取得好成绩而学习等）"),
  q("b2p-60", "Is disturbed by change of teacher or class",                                                                                          "对教师或课程的变动感到困扰"),
  q("b2p-61", "Has trouble organizing activities with friends",                                                                                      "在与朋友组织活动时遇到困难"),
  q("b2p-62", "Becomes too silly",                                                                                                                   "变得过于愚蠢"),
  q("b2p-63", "Leaves a trail of belongings wherever he/she goes",                                                                                   "他/她走到哪里都会留下一串物品"),
];

// ─── BRIEF-2 Self-Rating Form (55 items) ──────────────────────────────────────

export const BRIEF2_SELF_FORM: FormQuestion[] = [
  q("b2sr-1",  "I have trouble sitting still",                                                                                                                   "我很难保持静止"),
  q("b2sr-2",  "I have trouble accepting a different way to solve a problem with things such as schoolwork, friends, or tasks",                                   "我很难接受用不同的方式解决问题，比如学业、朋友或任务"),
  q("b2sr-3",  "When I am given three things to do, I remember only the first or last",                                                                          "当我被要求做三件事情时，我只记得第一项或最后一项"),
  q("b2sr-4",  "I am not aware of how my behavior affects or bothers others",                                                                                    "我不知道我的行为如何影响或打扰他人"),
  q("b2sr-5",  "My work is sloppy",                                                                                                                              "我的工作杂乱无序"),
  q("b2sr-6",  "I have angry outbursts",                                                                                                                         "我会发怒"),
  q("b2sr-7",  "I don't plan ahead for school assignments",                                                                                                      "我不会提前为学校作业做计划"),
  q("b2sr-8",  "I have difficulty finding my things (such as clothes, glasses, shoes, books, or pencils)",                                                       "我很难找到自己的东西（比如衣服、眼镜、鞋子、书或铅笔）"),
  q("b2sr-9",  "I have problems getting started on my own",                                                                                                      "我很难自行开始做事"),
  q("b2sr-10", "I am impulsive (I don't think before doing)",                                                                                                    "我冲动（不先考虑后果就行动）"),
  q("b2sr-11", "I have trouble getting used to new situations (such as classes, groups, or friends)",                                                             "我很难适应新情况（比如课程、小组或朋友）"),
  q("b2sr-12", "I have a short attention span",                                                                                                                  "我的注意力很短暂"),
  q("b2sr-13", "I have a poor understanding of my own strengths and weaknesses (I try things that are too difficult or too easy for me)",                         "我对自己的优势和劣势认识不足（我尝试太难或太简单的事情）"),
  q("b2sr-14", "I have outbursts for little reason",                                                                                                             "我偶尔会无缘无故发怒"),
  q("b2sr-15", "I get caught up in details and miss the main idea",                                                                                              "我会陷入细节中而忽略主要思想"),
  q("b2sr-16", "I get out of control more than my friends",                                                                                                      "我比朋友们更容易失控"),
  q("b2sr-17", "I get stuck on one topic or activity",                                                                                                           "我会执着于一个话题或活动"),
  q("b2sr-18", "I forget my name",                                                                                                                               "我会忘记自己的名字"),
  q("b2sr-19", "I have trouble with jobs or tasks that have more than one step",                                                                                  "我在面对需要多步骤的工作或任务时遇到困难"),
  q("b2sr-20", "I don't know when my actions bother others",                                                                                                     "我无法意识到自己的行为会让他人感到不适"),
  q("b2sr-21", "I have problems organizing my written work",                                                                                                     "我在组织书面作品时有困难"),
  q("b2sr-22", "I get upset over small events",                                                                                                                  "我会因小事而心烦意乱"),
  q("b2sr-23", "I have good ideas but do not get the job done (I lack follow-through)",                                                                          "我有很多好主意但却无法把事情做成（我缺乏执行力）"),
  q("b2sr-24", "I talk at the wrong time",                                                                                                                       "我总是在不合适的时候讲话"),
  q("b2sr-25", "I have trouble finishing tasks (such as chores or homework)",                                                                                    "我很难完成任务（比如家务或作业）"),
  q("b2sr-26", "I don't notice when my behavior causes negative reactions until it is too late",                                                                  "直到为时已晚我才意识到自己的行为会引起负面反应"),
  q("b2sr-27", "I overreact",                                                                                                                                    "我会过度反应"),
  q("b2sr-28", "I have trouble remembering things, even for a few minutes (such as directions or phone numbers)",                                                 "我很难记住事情，甚至只有几分钟（比如方向或电话号码）"),
  q("b2sr-29", "I make careless errors",                                                                                                                         "我常犯粗心错误"),
  q("b2sr-30", "I have problems waiting my turn",                                                                                                                "我很难等待轮到自己"),
  q("b2sr-31", "It bothers me when I have to deal with changes (such as routines, foods, or places)",                                                            "当必须面对变化时（比如日常安排、食物或地点），我感到不舒服"),
  q("b2sr-32", "I forget to hand in my homework, even when it's completed",                                                                                      "我即使完成作业也会忘记交上去"),
  q("b2sr-33", "I am slower than others when completing my work",                                                                                                "在完成工作时，我比别人慢"),
  q("b2sr-34", "I am easily overwhelmed",                                                                                                                        "我容易被打倒"),
  q("b2sr-35", "I don't plan ahead for future activities",                                                                                                       "我不会提前为未来活动做计划"),
  q("b2sr-36", "I have trouble counting to three",                                                                                                               "我很难数清楚到三"),
  q("b2sr-37", "I don't think ahead about possible problems",                                                                                                    "我不会提前考虑可能出现的问题"),
  q("b2sr-38", "I have difficulty finishing a task on my own",                                                                                                   "我很难独立完成任务"),
  q("b2sr-39", "I interrupt others",                                                                                                                             "我会打断别人"),
  q("b2sr-40", "I try the same approach to a problem over and over even when it does not work (I get stuck)",                                                    "当遇到问题时，我会一遍又一遍地采用同样的方法（卡住了）"),
  q("b2sr-41", "I forget instructions easily",                                                                                                                   "我容易忘记指示"),
  q("b2sr-42", "It takes me longer to complete my work",                                                                                                         "我完成工作需要更长时间"),
  q("b2sr-43", "My eyes fill with tears quickly over little things",                                                                                             "我因小事而眼泪汪汪"),
  q("b2sr-44", "I have problems completing my work",                                                                                                             "我很难完成我的工作"),
  q("b2sr-45", "I have trouble thinking of a different way to solve a problem when I get stuck",                                                                 "当陷入困境时，我很难考虑不同的解决问题的方式"),
  q("b2sr-46", "I am absentminded (forgetful)",                                                                                                                  "我常常心不在焉（健忘）"),
  q("b2sr-47", "I have trouble prioritizing (ordering) my activities",                                                                                           "我难以确定（列出）活动的优先顺序"),
  q("b2sr-48", "I think or talk out loud when working",                                                                                                          "当工作时，我会想或说出声"),
  q("b2sr-49", "I don't think of consequences before acting",                                                                                                    "我在行动之前不会考虑后果"),
  q("b2sr-50", "I am unaware of my behavior when I am in a group",                                                                                               "我在团队中时不自觉地表现自己"),
  q("b2sr-51", "I have trouble changing from one activity to another",                                                                                           "我很难从一个活动过渡到另一个"),
  q("b2sr-52", "I have trouble carrying out the things that are needed to reach a goal (such as saving money for special items or studying to get good grades)",  "我很难完成达到目标所需的事情（比如为特殊物品存钱或为了好成绩而学习）"),
  q("b2sr-53", "I have difficulty coming up with different ways of solving a problem",                                                                           "我很难想到不同的问题解决方式"),
  q("b2sr-54", "I cannot find the front door of my home",                                                                                                        "我找不到家门前"),
  q("b2sr-55", "I have problems finishing long-term projects (such as papers or book reports)",                                                                   "我难以完成长期项目（比如论文或书评报告）"),
];

// ─── BRIEF-2 Teacher Form (63 items) ──────────────────────────────────────────

export const BRIEF2_TEACHER_FORM: FormQuestion[] = [
  q("b2t-1",  "Is fidgety",                                                                                                                         "烦躁不安"),
  q("b2t-2",  "Resists or has trouble accepting a different way to solve a problem with schoolwork, friends, tasks, etc.",                            "抵制或在解决学校作业、朋友、任务等方面的问题时有困难接受不同的解决方式"),
  q("b2t-3",  "When given three things to do, remembers only the first or last",                                                                     "在给定三件事情要做时，只记得第一件或最后一件"),
  q("b2t-4",  "Is unaware of how his/her behavior affects or bothers others",                                                                        "不知道自己的行为如何影响或打扰他人"),
  q("b2t-5",  "Work is sloppy",                                                                                                                      "工作草率"),
  q("b2t-6",  "Has explosive, angry outbursts",                                                                                                      "爆炸性、愤怒的发作"),
  q("b2t-7",  "Does not plan ahead for school assignments",                                                                                          "不提前计划学校作业"),
  q("b2t-8",  "Cannot find things in desk",                                                                                                          "在书桌上找不到东西"),
  q("b2t-9",  "Is not a self-starter",                                                                                                               "不是自我启动者"),
  q("b2t-10", "Does not think before doing (is impulsive)",                                                                                          "做事不先考虑（冲动）"),
  q("b2t-11", "Has trouble getting used to new situations (classes, groups, friends, etc.)",                                                          "在适应新环境（课程、团体、朋友等）时遇到困难"),
  q("b2t-12", "Has a short attention span",                                                                                                          "注意力不集中"),
  q("b2t-13", "Has poor understanding of own strengths and weaknesses",                                                                              "对自身的优点和缺点了解不清楚"),
  q("b2t-14", "Has outbursts for little reason",                                                                                                     "缘由微末事发脾气"),
  q("b2t-15", "Gets caught up in details and misses the big picture",                                                                                "陷入细节中，忽略大局"),
  q("b2t-16", "Gets out of control more than friends",                                                                                               "比朋友更容易失控"),
  q("b2t-17", "Gets stuck on one topic or activity",                                                                                                 "容易被一个话题或活动困住"),
  q("b2t-18", "Forgets his/her name",                                                                                                                "忘记自己的名字"),
  q("b2t-19", "Has trouble with tasks that have more than one step",                                                                                  "难以完成多步骤任务"),
  q("b2t-20", "Does not realize that certain actions bother others",                                                                                  "没意识到自己的某些行为会打扰他人"),
  q("b2t-21", "Written work is poorly organized",                                                                                                    "书面工作组织混乱"),
  q("b2t-22", "Small events trigger big reactions",                                                                                                   "小事引发大反应"),
  q("b2t-23", "Has good ideas but does not get job done (lacks follow-through)",                                                                     "拥有好主意但无法完成任务（缺乏执行力）"),
  q("b2t-24", "Talks at the wrong time",                                                                                                             "错过说话时机"),
  q("b2t-25", "Has trouble finishing tasks (assignments, homework, etc.)",                                                                            "完成任务困难（作业、功课等）"),
  q("b2t-26", "Does not notice when his/her behavior causes negative reactions",                                                                     "注意不到自己的行为引起了负面反应"),
  q("b2t-27", "Reacts more strongly to situations than other children",                                                                              "对情况的反应比其他孩子更强烈"),
  q("b2t-28", "Has trouble remembering things, even for a few minutes",                                                                              "记忆中的事情困难，甚至只有几分钟"),
  q("b2t-29", "Makes careless errors",                                                                                                               "粗心造成错误"),
  q("b2t-30", "Gets out of seat at the wrong times",                                                                                                 "错误时起立"),
  q("b2t-31", "Becomes upset with new situations",                                                                                                   "对新情况感到困扰"),
  q("b2t-32", "Has trouble concentrating on schoolwork, etc.",                                                                                       "难以集中精力完成学业等任务"),
  q("b2t-33", "Has poor handwriting",                                                                                                                "笔迹潦草"),
  q("b2t-34", "Mood changes frequently",                                                                                                             "心情经常变化"),
  q("b2t-35", "Has good ideas but cannot get them on paper",                                                                                         "有好点子但无法写下来"),
  q("b2t-36", "Has trouble counting to three",                                                                                                       "数到三有困难"),
  q("b2t-37", "Leaves messes that others have to clean up",                                                                                          "留下别人必须打扫的混乱"),
  q("b2t-38", "Needs to be told to begin a task even when willing",                                                                                  "即使愿意也需要被告知开始任务"),
  q("b2t-39", "Acts too wild or \"out of control\"",                                                                                                 "行为过于狂野或\"失控\""),
  q("b2t-40", "Thinks too much about the same topic",                                                                                                "过度考虑同一个话题"),
  q("b2t-41", "Forgets what he/she was doing",                                                                                                       "忘记自己正在做什么"),
  q("b2t-42", "Does not check work for mistakes",                                                                                                    "不检查工作中的错误"),
  q("b2t-43", "Angry or tearful outbursts are intense but end suddenly",                                                                             "愤怒或哭泣的发作激烈但突然结束"),
  q("b2t-44", "Becomes overwhelmed by large assignments",                                                                                            "大型任务使之无法承受"),
  q("b2t-45", "Loses lunch box, lunch money, permission slips, homework, etc.",                                                                      "丢失午餐盒、午餐钱、许可证、家庭作业等"),
  q("b2t-46", "Needs help from an adult to stay on task",                                                                                            "需要成人帮助保持专注"),
  q("b2t-47", "Forgets to hand in homework, even when completed",                                                                                    "即使完成，也会忘记交作业"),
  q("b2t-48", "Has trouble putting the brakes on his/her actions",                                                                                   "难以控制自己的行为"),
  q("b2t-49", "Resists change of routine, foods, places, etc.",                                                                                      "抵制日常变化、食物、地点等"),
  q("b2t-50", "Has trouble getting started on work",                                                                                                 "很难开始工作"),
  q("b2t-51", "Mood is easily influenced by the situation",                                                                                          "心情很容易受环境影响"),
  q("b2t-52", "Underestimates time needed to finish tasks",                                                                                          "低估完成任务所需的时间"),
  q("b2t-53", "Does not bring home homework, assignment sheets, materials, etc.",                                                                     "不带回家作业、作业单、材料等"),
  q("b2t-54", "Cannot find the front door of school",                                                                                                "找不到学校的正门"),
  q("b2t-55", "Does not take initiative",                                                                                                            "不主动"),
  q("b2t-56", "Becomes upset too easily",                                                                                                            "很容易心烦意乱"),
  q("b2t-57", "Starts assignments at the last minute",                                                                                               "在最后一刻开始任务"),
  q("b2t-58", "Does not think of consequences before acting",                                                                                        "在行动之前不考虑后果"),
  q("b2t-59", "Is unaware of own behavior when in a group",                                                                                          "在团体中不自知自己的行为"),
  q("b2t-60", "Has problems coming up with different ways of solving a problem",                                                                     "解决问题时想不出不同的方法"),
  q("b2t-61", "Tests poorly even when knows correct answers",                                                                                        "即使知道正确答案，考试表现糟糕"),
  q("b2t-62", "Leaves work incomplete",                                                                                                              "留下未完成的工作"),
  q("b2t-63", "Has trouble thinking of a different way to solve a problem when stuck",                                                               "在困难时难以想出不同的解决方法"),
];
