export interface FormQuestion {
  id: string;
  text: string;
  textChinese?: string;
  textKorean?: string;
  type: "likert" | "yes_no" | "text" | "textarea" | "scale" | "checkbox_group" | "select" | "date" | "signature" | "radio_group" | "section_header" | "number" | "frequency_grid";
  options?: string[];
  optionsChinese?: string[];
  optionsKorean?: string[];
  rows?: FormQuestion[];
  domain: string;
  required?: boolean;
  conditionalOn?: string;
  conditionalValue?: string;
  note?: string;
  noteChinese?: string;
  noteKorean?: string;
}

const LIKERT_OPTIONS = ["Never", "Rarely", "Sometimes", "Often", "Very Often"];
const LIKERT_OPTIONS_ZH = ["从不", "很少", "有时", "经常", "非常频繁"];
const LIKERT_OPTIONS_KO = ["전혀 없음", "거의 없음", "때때로", "자주", "매우 자주"];

// ─── REFERRAL FORM ─────────────────────────────────────────────────────────────
export const REFERRAL_FORM: FormQuestion[] = [
  {
    id: "referrer_type",
    text: "I am a...",
    textChinese: "我是一个...",
    textKorean: "저는...",
    type: "radio_group",
    options: ["Parent", "School Personnel"],
    optionsChinese: ["家长", "学校工作人员"],
    optionsKorean: ["부모", "학교 직원"],
    domain: "referrer",
    required: true,
  },
  {
    id: "school_name",
    text: "ReMynd™ Network School Name",
    textChinese: "ReMynd™ 认证学校名称",
    textKorean: "ReMynd™ 네트워크 학교 이름",
    type: "select",
    options: [
      "Malvern College Chengdu",
      "Chengdu Montpellier International School (MIS)",
      "BASIS International & Bilingual School Chengdu",
      "QSI Chengdu",
      "QSI International School of Haiphong",
      "CDIS Chengdu",
      "CDUT Chengdu",
      "Chengdu Seventh Middle School — International Department",
      "Chengdu Shude Middle / High School — International Department",
      "Chengdu Foreign Languages School – International Division",
      "Dibang Kensi School, Chengdu",
      "SPGS International School Chengdu",
      "Leman International School Chengdu",
      "ISA Guangzhou",
      "Cloud 9 Kindergarten Chengdu",
      "BIBS Chengdu",
      "Dipont KCS Chengdu (King's College School, Chengdu)",
      "Westminster School Chengdu",
      "Chengdu Ottawa Public International School",
      "Qingdao Amerasia International School",
      "Sheko International School",
      "ISNSZ Shenzhen",
      "Achieve Xiamen International School",
      "Foshan EtonHouse International School",
      "NanJing EtonHouse International School",
      "Suzhou EtonHouse International School",
      "Changchun American International School",
      "Jinan Thomas International School",
      "Boren Sino Canadian School",
      "Beijing Huijia Private school",
      "Mountain Kingston Bilingual School",
      "EatonHouse Suzhou",
      "Nanjing International School",
    ],
    domain: "school",
    required: true,
  },
  {
    id: "student_english_name",
    text: "Student's English Name (Optional)",
    textChinese: "学生英文姓名 (可选)",
    textKorean: "학생 영어 이름 (선택)",
    type: "text",
    domain: "student",
  },
  {
    id: "student_chinese_first",
    text: "Student's Chinese First Name (Pinyin)",
    textChinese: "学生的中文名字",
    textKorean: "학생 중국어 이름 (핀인)",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_chinese_family",
    text: "Student's Chinese Family Name (Pinyin)",
    textChinese: "学生的中国姓",
    textKorean: "학생 중국어 성 (핀인)",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "parent_name",
    text: "Parent's Name (Pinyin)",
    textChinese: "父母的名字",
    textKorean: "부모 이름 (핀인)",
    type: "text",
    domain: "parent",
    required: true,
  },
  {
    id: "parent_email",
    text: "Parent's Email",
    textChinese: "家长邮箱",
    textKorean: "부모 이메일",
    type: "text",
    domain: "parent",
    required: true,
  },
  {
    id: "wechat",
    text: "WeChat",
    textChinese: "微信",
    textKorean: "위챗",
    type: "text",
    domain: "parent",
    required: true,
  },
  {
    id: "student_grade",
    text: "Student's Homeroom / Class",
    textChinese: "学生班级",
    textKorean: "학생 학급/반",
    type: "select",
    options: ["K", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8", "G9", "G10", "G11", "G12"],
    domain: "student",
    required: true,
  },
  {
    id: "student_age",
    text: "Student's Age",
    textChinese: "学生的年龄",
    textKorean: "학생 나이",
    type: "number",
    domain: "student",
    required: true,
  },
  {
    id: "student_dob",
    text: "Student's Date of Birth",
    textChinese: "学生出生日期",
    textKorean: "학생 생년월일",
    type: "date",
    domain: "student",
    required: true,
  },
  {
    id: "today_date",
    text: "Today's Date",
    textChinese: "今日日期",
    textKorean: "오늘 날짜",
    type: "date",
    domain: "referral",
    required: true,
  },
  {
    id: "behavior_locations",
    text: "Where do these behaviors usually take place?",
    textChinese: "这些行为通常发生在哪里?",
    textKorean: "이러한 행동은 주로 어디서 발생합니까?",
    type: "checkbox_group",
    options: [
      "During Classroom Time",
      "Morning Break",
      "Lunchtime",
      "Afternoon Break",
      "During ASA",
      "In Boarding",
      "On School Bus",
      "On a Field Trip",
      "At Camp",
      "Not Applicable",
    ],
    optionsChinese: [
      "课堂时间",
      "上午休息时间",
      "午餐时间",
      "下午休息时间",
      "课外课时间",
      "在宿舍时间",
      "在校车时间",
      "实地考察旅行期间",
      "在露营期间",
      "不适用",
    ],
    optionsKorean: [
      "수업 중",
      "오전 휴식",
      "점심 시간",
      "오후 휴식",
      "방과 후 활동 중",
      "기숙사에서",
      "스쿨버스에서",
      "현장 학습 중",
      "캠프에서",
      "해당 없음",
    ],
    domain: "referral",
  },
  {
    id: "teacher1_name",
    text: "Teacher 1 Name (English or Pinyin)",
    textChinese: "老师1名",
    textKorean: "교사 1 이름 (영어 또는 핀인)",
    type: "text",
    domain: "teachers",
    required: true,
  },
  {
    id: "teacher1_email",
    text: "Teacher 1 Email",
    textChinese: "电子邮件",
    textKorean: "교사 1 이메일",
    type: "text",
    domain: "teachers",
    required: true,
  },
  {
    id: "teacher2_name",
    text: "Teacher 2 Name (English or Pinyin)",
    textChinese: "老师2名",
    textKorean: "교사 2 이름 (영어 또는 핀인)",
    type: "text",
    domain: "teachers",
  },
  {
    id: "teacher2_email",
    text: "Teacher 2 Email",
    textChinese: "老师2电子邮件",
    textKorean: "교사 2 이메일",
    type: "text",
    domain: "teachers",
  },
  {
    id: "teacher3_name",
    text: "Teacher 3 Name (English or Pinyin)",
    textChinese: "老师3名",
    textKorean: "교사 3 이름 (영어 또는 핀인)",
    type: "text",
    domain: "teachers",
  },
  {
    id: "teacher3_email",
    text: "Teacher 3 Email",
    textChinese: "老师3电子邮件",
    textKorean: "교사 3 이메일",
    type: "text",
    domain: "teachers",
  },
  {
    id: "details",
    text: "Please give details including any dates of occurrence",
    textChinese: "请提供详细信息，包括任何发生的日期",
    textKorean: "발생 날짜를 포함한 자세한 내용을 기재해 주세요",
    type: "textarea",
    domain: "referral",
  },
  {
    id: "student_history",
    text: "Student Details (Check all that apply)",
    textChinese: "学生详细信息 (检查所有适用的内容)",
    textKorean: "학생 정보 (해당하는 모든 항목 체크)",
    type: "checkbox_group",
    options: [
      "The student has been referred for counselling before",
      "The student is currently seeing a mental health professional",
      "The student is currently on medication",
    ],
    optionsChinese: [
      "这名学生以前曾被转介咨询过",
      "该学生目前正在看心理健康专家",
      "这名学生目前正在服药",
    ],
    optionsKorean: [
      "이 학생은 이전에 상담을 위해 의뢰된 적이 있습니다",
      "이 학생은 현재 정신건강 전문가를 만나고 있습니다",
      "이 학생은 현재 약을 복용하고 있습니다",
    ],
    domain: "referral",
  },
  {
    id: "actions_taken",
    text: "Actions Already Taken",
    textChinese: "已采取的行动",
    textKorean: "이미 취한 조치",
    type: "checkbox_group",
    options: [
      "Discussed with Student",
      "Made note in Student Diary / Contacted Parents",
      "Consulted Home Room / Subject Teacher",
      "Consulted Assistant Principal",
      "Consulted EAL Coordinator",
      "Implemented EAL Strategies",
      "Implemented Behavior Management Strategies",
      "Implemented Differentiation Strategies",
      "Consulted School Counselor / Pastoral Care",
      "Consulted Learning Enhancement Staff",
      "Consulted School Nurse",
      "Logged into Managebac",
      "Other",
    ],
    optionsChinese: [
      "和学生进行了交流",
      "在学生的家校交流本上做了记录/联系了父母",
      "咨询家庭室/学科老师",
      "和校长助理进行了沟通",
      "和EAL协调员进行了沟通",
      "采取了EAL的策略",
      "采取了行为管理策略",
      "采取了因材施教策略",
      "咨询学校辅导员",
      "与学习促进老师进行了沟通",
      "与校医进行了沟通",
      "Managebac已登陆",
      "其他",
    ],
    optionsKorean: [
      "학생과 논의",
      "학생 수첩에 기록/부모 연락",
      "담임/교과 교사 상담",
      "교감 상담",
      "EAL 코디네이터 상담",
      "EAL 전략 실행",
      "행동 관리 전략 실행",
      "차별화 전략 실행",
      "학교 상담사/학생 복지 상담",
      "학습 지원 직원 상담",
      "학교 보건 교사 상담",
      "ManageBac에 기록",
      "기타",
    ],
    domain: "referral",
    required: true,
  },
  {
    id: "reason_for_referral",
    text: "Reason for Referral",
    textChinese: "推荐的理由",
    textKorean: "의뢰 이유",
    type: "checkbox_group",
    options: [
      "School adjustment",
      "Gifted / Grade acceleration",
      "Motivation",
      "Learning difficulties",
      "Disruptive behavior",
      "School refusal",
      "Anxiety",
      "Depression",
      "Low self-esteem",
      "Personal care",
      "Academic progress",
      "Time management",
      "Aggression",
      "Bullying",
      "Anger",
      "Social skills",
      "Poor peer relationships",
      "Home problems",
      "Withdrawn",
      "Stealing",
      "Perfectionist",
      "Fearful",
      "Obscene language",
      "Substance abuse",
      "Self-Harm",
      "Other",
    ],
    optionsChinese: [
      "学校调整",
      "天赋/年级加速度",
      "动机",
      "学习困难",
      "破坏性行为",
      "学校拒绝",
      "焦虑",
      "抑郁症",
      "低自尊",
      "个人护理",
      "学术的进步",
      "时间管理",
      "侵略",
      "欺凌",
      "愤怒",
      "社会技能",
      "同伴关系差",
      "家里的问题",
      "撤销",
      "偷",
      "完美主义者",
      "恐惧",
      "淫秽语言",
      "物质滥用",
      "自残",
      "其他",
    ],
    optionsKorean: [
      "학교 적응",
      "영재/학년 가속",
      "학습 동기",
      "학습 어려움",
      "수업 방해 행동",
      "등교 거부",
      "불안",
      "우울",
      "낮은 자존감",
      "개인 위생",
      "학업 진도",
      "시간 관리",
      "공격성",
      "괴롭힘",
      "분노",
      "사회적 기술",
      "또래 관계 불량",
      "가정 문제",
      "위축된 행동",
      "도둑질",
      "완벽주의",
      "두려움",
      "불건전한 언어 사용",
      "약물 남용",
      "자해",
      "기타",
    ],
    domain: "referral",
    required: true,
  },
  {
    id: "general_concern_category",
    text: "General Concern Category (Check all that apply)",
    textChinese: "总体类别 (请检查所有适用的)",
    textKorean: "일반 관심 카테고리 (해당하는 모든 항목 체크)",
    type: "checkbox_group",
    options: [
      "Academic / Learning Support / EAL",
      "Social Skills",
      "Fighting / Bullying",
      "Emotional Support",
      "Family-Related Issues",
      "Crisis Intervention (Urgent)",
      "Other",
    ],
    optionsChinese: [
      "学习方面的支持",
      "社交技能",
      "校园霸陵",
      "情感支持",
      "与家庭因素相关",
      "危机干预（紧急）",
      "其他",
    ],
    optionsKorean: [
      "학습/학업 지원/EAL",
      "사회적 기술",
      "싸움/괴롭힘",
      "정서적 지원",
      "가족 관련 문제",
      "위기 개입 (긴급)",
      "기타",
    ],
    domain: "referral",
    required: true,
  },
  {
    id: "additional_comments",
    text: "Additional Comments",
    textChinese: "额外的评论",
    textKorean: "추가 의견",
    type: "textarea",
    domain: "referral",
  },
];

// ─── CONSENT FORM ──────────────────────────────────────────────────────────────
export const CONSENT_FORM: FormQuestion[] = [
  {
    id: "student_first_name",
    text: "First / Given Name of Student",
    textChinese: "学生姓名",
    textKorean: "학생 이름",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_last_name",
    text: "Last / Family Name of Student",
    textChinese: "学生姓名（姓）",
    textKorean: "학생 성",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_email",
    text: "Email Address of Student",
    textChinese: "学生邮箱",
    textKorean: "학생 이메일 주소",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_dob",
    text: "Student's Date of Birth",
    textChinese: "学生出生日期",
    textKorean: "학생 생년월일",
    type: "date",
    domain: "student",
    required: true,
  },
  {
    id: "consent_note",
    text: "I am the parent / legal guardian of the above-named student, who wishes to take a student assessment conducted by ReMynd Student Services, and its contracted providers. I understand and acknowledge that all individuals planning to take the assessment are required to agree to all of the terms and conditions contained herein, and that these terms and conditions are legally binding.",
    textChinese: "我是上述学生的父母或监护人，我同意学生参加由ReMynd学生服务及其合作伙伴提供的学生评估。我理解并确认所有计划参加评估的人员均需同意本协议中列出的所有条款和条件，并承认这些条款和条件具有法律约束力。",
    textKorean: "저는 위에 명시된 학생의 부모/법정 후견인으로서, ReMynd 학생 서비스 및 계약된 제공자가 실시하는 학생 평가에 학생이 참여하는 것에 동의합니다. 평가를 받을 계획인 모든 사람은 본 약관에 포함된 모든 조건에 동의해야 하며, 이 조건들은 법적 구속력이 있음을 이해하고 인정합니다.",
    type: "section_header",
    domain: "consent",
  },
  {
    id: "consent_1",
    text: "1. I hereby authorize the above named student to take the assessment; to have all his relevant teachers fill out any necessary forms and questionnaires; to have his school release any relevant past and/or current school records, videos, and work product.",
    textChinese: "1. 我特此授权上述学生参加评估；让他的所有相关教师填写任何必要的表格和问卷；并允许他的学校释放任何相关的过去和/或当前的学校记录、视频和工作成果。",
    textKorean: "1. 저는 위에 명시된 학생이 평가를 받도록 허가합니다. 관련된 모든 교사들이 필요한 양식과 설문지를 작성하고, 학교가 관련 과거 및/또는 현재의 학교 기록, 비디오 및 작업물을 공개하는 것을 허가합니다.",
    type: "radio_group",
    options: ["Yes", "No"],
    optionsKorean: ["예", "아니오"],
    domain: "consent",
    required: true,
  },
  {
    id: "consent_2",
    text: "2. I confirm that I completely understand the assessment process as it has been explained to me, including, but not limited to, those provisions relating to testing, privacy policies, the collection, processing, use, and transmission of the student's personally identifiable data (including any digital photographs, signatures, and audio/video recordings collected during testing), and disclosure of such data to ReMynd Student Services, its partners, service providers, any score recipients you select, and others as necessary to prevent unlawful activity or as required by law.",
    textChinese: "2. 我确认我完全理解评估过程，包括但不限于与测试、隐私政策、学生可识别性数据的收集、处理、使用和传输，以及向ReMynd学生服务及其合作伙伴的披露等相关条款。",
    textKorean: "2. 저는 평가 과정을 완전히 이해함을 확인합니다. 여기에는 테스트, 개인정보 보호 정책, 학생의 개인 식별 가능 데이터(테스트 중 수집된 디지털 사진, 서명, 오디오/비디오 녹화 포함)의 수집, 처리, 사용 및 전송, 그리고 ReMynd 학생 서비스 및 파트너에게 공개하는 것이 포함됩니다.",
    type: "radio_group",
    options: ["Yes", "No"],
    optionsKorean: ["예", "아니오"],
    domain: "consent",
    required: true,
  },
  {
    id: "consent_3",
    text: "3. I understand and consent to the use of AI technology, including but not limited to platforms such as Bobby-AI, BastionGPT, and NoteZap, to assist in summarizing information and making written documentation more accessible to families. I acknowledge that the results generated by these AI platforms will be thoroughly vetted and edited for accuracy. I understand that while all companies handling our protected health information are HIPAA-compliant or have signed a business associate agreement (BAA) to ensure confidentiality, there is always a small risk when data is exchanged that confidential information could be leaked.",
    textChinese: "3. 我理解并同意使用人工智能技术，包括但不限于Bobby-AI、BastionGPT和NoteZap等平台，以协助总结信息并使书面文件对家庭更易于获取。我承认这些人工智能平台生成的结果将经过严格审查和编辑以确保准确性。",
    textKorean: "3. 저는 Bobby-AI, BastionGPT, NoteZap 등의 AI 기술 플랫폼을 활용하여 정보를 요약하고 서면 문서를 가족에게 더 접근하기 쉽게 만드는 것에 이해하고 동의합니다. AI 플랫폼이 생성한 결과물은 정확성을 위해 철저히 검토 및 편집될 것임을 인지합니다. 보호된 건강 정보를 처리하는 모든 회사가 HIPAA를 준수하거나 비밀 유지를 위한 사업 관련 계약(BAA)에 서명하였더라도 데이터 교환 시 기밀 정보가 유출될 소지가 있음을 이해합니다.",
    type: "radio_group",
    options: ["Yes", "No"],
    optionsKorean: ["예", "아니오"],
    domain: "consent",
    required: true,
  },
  {
    id: "consent_4",
    text: "4. I consent to, and agree that the above named student will comply with and be bound by, all of the terms and conditions herein.",
    textChinese: "4. 我同意并确认上述提到的学生将遵守并受本条款和条件的约束。",
    textKorean: "4. 저는 위에 명시된 학생이 본 약관의 모든 조건을 준수하고 이에 구속될 것에 동의합니다.",
    type: "radio_group",
    options: ["Yes", "No"],
    optionsKorean: ["예", "아니오"],
    domain: "consent",
    required: true,
  },
  {
    id: "guardian_name",
    text: "Name of Parent / Legal Guardian (Signature)",
    textChinese: "监护人姓名（签名）",
    textKorean: "부모/법정 후견인 이름 (서명)",
    type: "signature",
    note: "By writing your name in this box, you agree and attest to the truthfulness and validity of the information in this consent form and give your consent for the above named student to be assessed.",
    noteChinese: "在此框中填写您的姓名，即表示您同意并证明此同意书中的信息是真实和有效的，並授權進行上述學生的評估。",
    noteKorean: "이 상자에 이름을 기재함으로써, 귀하는 이 동의서의 정보가 사실이고 유효함에 동의하며, 위에 명시된 학생이 평가를 받는 것에 동의합니다.",
    domain: "consent",
    required: true,
  },
  {
    id: "consent_date",
    text: "Date",
    textChinese: "日期",
    textKorean: "날짜",
    type: "date",
    domain: "consent",
    required: true,
  },
];

// ─── INTAKE FORM ───────────────────────────────────────────────────────────────
export const INTAKE_FORM: FormQuestion[] = [
  // Section 1: Basic Info
  {
    id: "section_basic",
    text: "Basic Information",
    textChinese: "基本资料",
    textKorean: "기본 정보",
    type: "section_header",
    domain: "basic",
    note: "Please provide copies of any prior evaluations and past school reports. IMPORTANT: All forms need to be submitted in time for the FIRST day of assessment.",
    noteChinese: "请您附上孩子曾有的评估报告和孩子过往的学校成绩表，并于心理测量的首天与此表格一同提交。",
    noteKorean: "이전 평가 보고서와 학교 성적표 사본을 제출해 주세요. 중요: 모든 양식은 평가 첫날까지 제출되어야 합니다.",
  },
  { id: "child_last_name", text: "Child's Last Name", textChinese: "姓", textKorean: "아동 성", type: "text", domain: "basic", required: true },
  { id: "child_first_name", text: "Child's First Name", textChinese: "名", textKorean: "아동 이름", type: "text", domain: "basic", required: true },
  { id: "child_middle_name", text: "Child's Middle Name", textChinese: "中间名", textKorean: "아동 중간 이름", type: "text", domain: "basic" },
  { id: "child_english_name", text: "Child's English Name", textChinese: "英文名", textKorean: "아동 영어 이름", type: "text", domain: "basic" },
  { id: "dob", text: "Date of Birth", textChinese: "出生日期", textKorean: "생년월일", type: "date", domain: "basic", required: true },
  { id: "school", text: "School", textChinese: "学校", textKorean: "학교", type: "text", domain: "basic", required: true },
  { id: "home_telephone", text: "Home Telephone", textChinese: "家庭电话", textKorean: "집 전화번호", type: "text", domain: "basic", required: true },
  { id: "home_address", text: "Home Address", textChinese: "家庭住址", textKorean: "집 주소", type: "text", domain: "basic", required: true },
  { id: "other_doctors_medication", text: "Other Doctors / Current Medication", textChinese: "其他医生/目前用药", textKorean: "담당 의사/현재 복용 중인 약물", type: "textarea", domain: "basic" },
  {
    id: "child_lives_with",
    text: "The child lives with",
    textChinese: "同孩子共同生活的人",
    textKorean: "아동과 함께 거주하는 사람",
    type: "checkbox_group",
    options: ["Both parents", "Mother", "Father", "Other"],
    optionsChinese: ["父母", "母亲", "父亲", "其他人"],
    optionsKorean: ["양부모", "어머니", "아버지", "기타"],
    domain: "basic",
    required: true,
  },
  { id: "child_email", text: "Child's Email Address", textChinese: "孩子电邮", textKorean: "아동 이메일 주소", type: "text", domain: "basic" },
  { id: "child_mobile", text: "Child's Mobile Number", textChinese: "孩子电话", textKorean: "아동 휴대폰 번호", type: "text", domain: "basic" },

  // Family Members
  {
    id: "section_family_members",
    text: "Family Members (Siblings)",
    textChinese: "家庭成员（包括兄弟姐妹）",
    textKorean: "가족 구성원 (형제/자매)",
    type: "section_header",
    domain: "family",
  },
  { id: "sibling1_name", text: "Sibling 1 — Name", textChinese: "成员1 — 名字", textKorean: "형제/자매 1 — 이름", type: "text", domain: "family" },
  { id: "sibling1_relationship", text: "Sibling 1 — Relationship", textChinese: "关系", textKorean: "관계", type: "text", domain: "family" },
  { id: "sibling1_age", text: "Sibling 1 — Age", textChinese: "年龄", textKorean: "나이", type: "number", domain: "family" },
  { id: "sibling2_name", text: "Sibling 2 — Name", textChinese: "成员2 — 名字", textKorean: "형제/자매 2 — 이름", type: "text", domain: "family" },
  { id: "sibling2_relationship", text: "Sibling 2 — Relationship", textChinese: "关系", textKorean: "관계", type: "text", domain: "family" },
  { id: "sibling2_age", text: "Sibling 2 — Age", textChinese: "年龄", textKorean: "나이", type: "number", domain: "family" },
  { id: "sibling3_name", text: "Sibling 3 — Name", textChinese: "成员3 — 名字", textKorean: "형제/자매 3 — 이름", type: "text", domain: "family" },
  { id: "sibling3_relationship", text: "Sibling 3 — Relationship", textChinese: "关系", textKorean: "관계", type: "text", domain: "family" },
  { id: "sibling3_age", text: "Sibling 3 — Age", textChinese: "年龄", textKorean: "나이", type: "number", domain: "family" },

  // Parents
  {
    id: "section_parents",
    text: "Parent / Guardian Information",
    textChinese: "父母/监护人信息",
    textKorean: "부모/후견인 정보",
    type: "section_header",
    domain: "parents",
  },
  { id: "father_name", text: "Name of Father / Stepfather", textChinese: "父亲/继父名字", textKorean: "아버지/양아버지 이름", type: "text", domain: "parents" },
  { id: "father_mobile", text: "Father's Mobile Phone", textChinese: "父亲的手机", textKorean: "아버지 휴대폰", type: "text", domain: "parents" },
  { id: "father_email", text: "Father's Email", textChinese: "父亲的电子邮件", textKorean: "아버지 이메일", type: "text", domain: "parents" },
  { id: "father_address", text: "Father's Home / Work Address", textChinese: "父亲的家庭/工作地址", textKorean: "아버지 자택/직장 주소", type: "text", domain: "parents" },
  { id: "father_occupation", text: "Father's Occupation / Employer", textChinese: "父亲的职业/雇主", textKorean: "아버지 직업/회사", type: "text", domain: "parents" },
  { id: "mother_name", text: "Name of Mother / Stepmother", textChinese: "母亲/继母名字", textKorean: "어머니/양어머니 이름", type: "text", domain: "parents" },
  { id: "mother_mobile", text: "Mother's Mobile Phone", textChinese: "母亲的手机", textKorean: "어머니 휴대폰", type: "text", domain: "parents" },
  { id: "mother_email", text: "Mother's Email", textChinese: "母亲的电子邮件", textKorean: "어머니 이메일", type: "text", domain: "parents" },
  { id: "mother_address", text: "Mother's Home / Work Address", textChinese: "母亲的家庭/工作地址", textKorean: "어머니 자택/직장 주소", type: "text", domain: "parents" },
  { id: "mother_occupation", text: "Mother's Occupation / Employer", textChinese: "母亲的职业/雇主", textKorean: "어머니 직업/회사", type: "text", domain: "parents" },

  // Referral Info
  {
    id: "section_referral",
    text: "Referral Information",
    textChinese: "推荐信息",
    textKorean: "의뢰 정보",
    type: "section_header",
    domain: "referral",
  },
  { id: "reason_for_testing", text: "Reason for Testing", textChinese: "接受测试原因", textKorean: "검사 이유", type: "textarea", domain: "referral", required: true },
  { id: "referred_by", text: "Referred By (Person / Organization)", textChinese: "推荐人/机构", textKorean: "의뢰인/기관", type: "text", domain: "referral" },
  { id: "previous_diagnosis", text: "Previous Diagnosis", textChinese: "过往诊断", textKorean: "이전 진단", type: "text", domain: "referral" },
  { id: "diagnosis_year", text: "Year of Diagnosis", textChinese: "诊断年份", textKorean: "진단 연도", type: "text", domain: "referral" },
  { id: "diagnosis_by", text: "Diagnosis Given By", textChinese: "诊症医生或机构", textKorean: "진단 기관/의사", type: "text", domain: "referral" },
  { id: "present_issues", text: "Present Issues — List major concerns / reasons for testing in your own words", textChinese: "请仔细描述孩子的现况或困难与主要接受测量的原因", textKorean: "현재 문제 — 검사 이유 및 주요 관심사를 본인의 말로 기술해 주세요", type: "textarea", domain: "referral", required: true },
  { id: "noticed_by_person", text: "When and by whom were these difficulties noticed — Person", textChinese: "何人察觉异状", textKorean: "어려움을 처음 발견한 사람", type: "text", domain: "referral" },
  { id: "noticed_approximate_time", text: "Approximate time difficulties have been present", textChinese: "状况维持的时间", textKorean: "어려움이 지속된 기간 (대략)", type: "text", domain: "referral" },
  { id: "behavior_effect", text: "What effect does the behavior have on the child and those around them?", textChinese: "这些行为如何影响孩子及其身边的人？", textKorean: "이러한 행동이 아동과 주변 사람들에게 어떤 영향을 미칩니까?", type: "textarea", domain: "referral" },

  // Behavioral Checklist
  {
    id: "section_behavior",
    text: "Behavioral Checklist — Check any that apply",
    textChinese: "请选择符合孩子情况的描述（多选）",
    textKorean: "행동 체크리스트 — 해당하는 항목 모두 선택",
    type: "section_header",
    domain: "behavior",
  },
  {
    id: "behavioral_checklist",
    text: "Behavioral Characteristics",
    textChinese: "行为特征",
    textKorean: "행동 특성",
    type: "checkbox_group",
    options: [
      "Cries easily", "Shy", "Disobedient", "Easily distracted", "Misbehaves at school",
      "Hurts others", "Seems Happy", "Complains about homework", "Affectionate",
      "Seems Immature for age", "Follows Instructions", "Polite", "Difficult",
      "Dislikes handwriting", "Fidgets", "Seems sad", "Finds Transitions Difficult",
      "Makes poor eye contact", "Has difficulty sustaining effort", "Loses personal items",
      "Procrastinates", "Popular", "Interrupts others", "Overly Sensitive", "Quick to Anger",
      "Tells Lies", "Disorganized", "Learns quickly", "Wets bed", "Complains about school",
      "Seeks Attention", "Overactive", "Stubborn", "Nurturing to younger kids", "Anxious",
      "Volatile", "Easily frustrated", "Outgoing", "Steals", "Misbehaves at home",
      "Argumentative", "Cooperative", "Has nightmares", "Overly dramatic",
      "Throws temper tantrums", "Bossy", "Eager to Please",
    ],
    optionsChinese: [
      "易哭", "害羞", "悖逆", "容易分神", "在校内不守纪律",
      "伤害别人", "看起来开心", "抱怨课业", "有丰富感情",
      "较同龄孩子不成熟", "听从指示", "有礼貌", "难以亲近",
      "不爱书写", "烦躁不安", "看起来忧伤", "适应力差",
      "说话时欠缺眼神接触", "欠缺恒心", "丢三落四",
      "爱拖延耽搁", "受欢迎", "打扰别人", "过于敏感", "容易动怒",
      "说谎", "做事欠条理", "学习速度快", "尿床", "抱怨学校",
      "爱引人注意", "过度活跃", "固执", "关心比自己小的孩童", "易焦虑",
      "善变", "容易沮丧", "外向好动", "有偷窃行为", "在家不守规矩",
      "喜好争辩", "乐于合作", "造噩梦", "戏剧性及浮夸行为",
      "乱发脾气", "专横", "渴望取悦他人",
    ],
    optionsKorean: [
      "쉽게 울음", "수줍음", "불순종", "쉽게 산만해짐", "학교에서 문제 행동",
      "타인을 해침", "행복해 보임", "숙제에 대해 불평", "애정이 풍부",
      "나이에 비해 미성숙해 보임", "지시를 따름", "예의 바름", "다루기 어려움",
      "필기를 싫어함", "안절부절못함", "슬퍼 보임", "전환이 어려움",
      "눈 맞춤이 부족", "지속적인 노력이 어려움", "물건을 잃어버림",
      "미루는 경향", "인기가 많음", "타인을 방해함", "과도하게 예민", "쉽게 화냄",
      "거짓말", "무질서", "빠르게 학습", "야뇨증", "학교에 대해 불평",
      "관심 끌기", "과활동", "고집스러움", "어린 아이에게 다정", "불안",
      "감정 기복", "쉽게 좌절", "외향적", "도둑질", "가정에서 문제 행동",
      "논쟁적", "협력적", "악몽", "지나치게 극적인 행동",
      "짜증 부리기", "권위적", "인정받으려 함",
    ],
    domain: "behavior",
  },
  { id: "strengths", text: "What are the child's strengths and positive qualities? What are they good at?", textChinese: "孩子有什么强项及优点？在学校、在家中、交际上、艺术上擅长之处是什么？", textKorean: "아동의 강점과 긍정적인 자질은 무엇입니까? 학교, 가정, 사회적, 예술적으로 잘하는 것이 무엇인가요?", type: "textarea", domain: "behavior" },

  // Developmental History
  {
    id: "section_developmental",
    text: "Developmental History",
    textChinese: "成长及发育历程",
    textKorean: "발달 역사",
    type: "section_header",
    domain: "developmental",
  },
  { id: "mother_age_at_birth", text: "Mother's Age at Child's Birth", textChinese: "母亲产子年龄", textKorean: "출산 시 어머니 나이", type: "number", domain: "developmental", required: true },
  { id: "father_age_at_birth", text: "Father's Age at Child's Birth", textChinese: "父亲在孩子出生时的年龄", textKorean: "출산 시 아버지 나이", type: "number", domain: "developmental" },
  { id: "pregnancy_length", text: "Length of Pregnancy", textChinese: "怀孕时间长短", textKorean: "임신 기간", type: "text", domain: "developmental" },
  { id: "birth_weight", text: "Birth Weight", textChinese: "孩子出生体重", textKorean: "출생 체중", type: "text", domain: "developmental" },
  { id: "condition_at_birth", text: "Condition at Birth", textChinese: "孩子出生状况", textKorean: "출생 시 상태", type: "text", domain: "developmental" },
  { id: "pregnancy_complications", text: "Were there any complications during pregnancy?", textChinese: "怀孕时的特别症状或并发症", textKorean: "임신 중 합병증이 있었습니까?", type: "textarea", domain: "developmental" },
  { id: "delivery_complications", text: "Were there any complications during delivery?", textChinese: "产子时的特别症状或并发症", textKorean: "출산 중 합병증이 있었습니까?", type: "textarea", domain: "developmental", required: true },
  {
    id: "anesthesia",
    text: "Anesthesia during childbirth",
    textChinese: "产子时的麻醉情况",
    textKorean: "출산 시 마취",
    type: "radio_group",
    options: ["None", "Local", "Epidural", "General"],
    optionsChinese: ["无麻醉", "局部麻醉", "无痛分娩", "全身麻醉"],
    optionsKorean: ["마취 없음", "국소 마취", "경막외 마취", "전신 마취"],
    domain: "developmental",
    required: true,
  },
  {
    id: "delivery_method",
    text: "Method of Delivery",
    textChinese: "产子方式",
    textKorean: "출산 방법",
    type: "radio_group",
    options: ["Natural", "Forceps", "Ventous Suction", "Caesarian Section"],
    optionsChinese: ["自然分娩", "产钳分娩", "吸道分娩", "剖腹分娩"],
    optionsKorean: ["자연 분만", "겸자 분만", "흡입 분만", "제왕절개"],
    domain: "developmental",
    required: true,
  },
  {
    id: "birth_problems",
    text: "Were any of the following problems present at birth?",
    textChinese: "有否发生以下状况？",
    textKorean: "출생 시 다음 문제가 있었습니까?",
    type: "checkbox_group",
    options: ["Breathing problems", "Cord around the neck", "Unusual color", "Problems feeding", "Problems sleeping"],
    optionsChinese: ["呼吸困难", "脐带缠颈", "脸色异常", "哺喂困难", "睡眠困难"],
    optionsKorean: ["호흡 문제", "탯줄이 목에 감김", "피부색 이상", "수유 문제", "수면 문제"],
    domain: "developmental",
  },
  {
    id: "motor_development",
    text: "Motor Development",
    textChinese: "行动发育",
    textKorean: "운동 발달",
    type: "radio_group",
    options: ["Delayed", "Typical", "Fast"],
    optionsChinese: ["迟缓", "正常", "较快"],
    optionsKorean: ["지연", "정상", "빠름"],
    domain: "developmental",
  },
  {
    id: "speech_development",
    text: "Speech and Linguistic Development",
    textChinese: "语言表达及说话能力发展",
    textKorean: "언어 및 말하기 발달",
    type: "radio_group",
    options: ["Delayed", "Typical", "Fast"],
    optionsChinese: ["迟缓", "正常", "较快"],
    optionsKorean: ["지연", "정상", "빠름"],
    domain: "developmental",
  },
  { id: "babble_age", text: "Approximate age when child started to babble", textChinese: "孩子初学会牙牙说话的年龄", textKorean: "아동이 옹알이를 시작한 대략적인 나이", type: "text", domain: "developmental" },
  { id: "talk_age", text: "Approximate age when child started to talk", textChinese: "孩子初学会说话的年龄", textKorean: "아동이 말을 시작한 대략적인 나이", type: "text", domain: "developmental" },
  {
    id: "self_help",
    text: "Self-help / Self-care Development",
    textChinese: "自理能力发育",
    textKorean: "자조/자기 관리 발달",
    type: "radio_group",
    options: ["Delayed", "Typical", "Fast"],
    optionsChinese: ["迟缓", "正常", "较快"],
    optionsKorean: ["지연", "정상", "빠름"],
    domain: "developmental",
  },
  { id: "toilet_age", text: "Approximate age when child started to use the toilet", textChinese: "孩子初学会如厕的年龄", textKorean: "아동이 화장실을 사용하기 시작한 대략적인 나이", type: "text", domain: "developmental" },
  { id: "dress_age", text: "Approximate age when child started to dress themselves", textChinese: "孩子初学会穿衣服的年龄", textKorean: "아동이 스스로 옷을 입기 시작한 대략적인 나이", type: "text", domain: "developmental" },
  {
    id: "infant_temperament",
    text: "Temperament as an infant / toddler (check all that apply)",
    textChinese: "婴孩/幼儿时期的性情（多选）",
    textKorean: "영아/유아기 기질 (해당하는 모든 항목 체크)",
    type: "checkbox_group",
    options: [
      "Fearful", "Curious", "Easy to manage", "Always Falling", "More interested in things than people",
      "Shy or Timid", "Into everything", "Alert", "Slow to warm up", "Does not engage in imaginative play",
      "Stubborn", "Affectionate", "Aggressive", "Breaks toys",
      "Plays next to kids rather than playing with them", "Impulsive", "Underactive",
      "Dare-Devil", "Overactive", "Rocking or repetitive motions",
    ],
    optionsChinese: [
      "恐惧", "好奇", "容易照料", "易受他人影响", "对事物比对人更有兴趣",
      "害羞", "对什么事都感兴趣", "警惕", "慢热", "不爱在自我想像中的情形玩乐和游戏",
      "固执", "情感丰富", "好斗", "爱把玩具弄坏",
      "在别的孩子旁玩而不与他们一起玩", "冲动", "过于静态",
      "胆子大", "过于好动", "有重复或摇晃的动作",
    ],
    optionsKorean: [
      "두려움", "호기심", "돌보기 쉬움", "자주 넘어짐", "사람보다 사물에 더 관심",
      "수줍음/소심함", "무엇이든 흥미", "경계심", "적응이 느림", "상상 놀이를 하지 않음",
      "고집스러움", "애정이 풍부", "공격적", "장난감을 부숨",
      "다른 아이 옆에서 노는 것을 선호", "충동적", "저활동",
      "무모한 도전", "과활동", "몸을 흔들거나 반복적인 움직임",
    ],
    domain: "developmental",
  },

  // Family History
  {
    id: "section_family_history",
    text: "Family History",
    textChinese: "家庭背景",
    textKorean: "가족 배경",
    type: "section_header",
    domain: "family_history",
  },
  { id: "home_members", text: "Who lives at home besides the child? (Names and relationships)", textChinese: "家中成员及其关系（如祖父母、佣人、兄弟姊妹等）", textKorean: "아동 외에 집에 함께 사는 사람은 누구입니까? (이름과 관계)", type: "textarea", domain: "family_history" },
  { id: "living_with_bio_parents", text: "Is the child living with his/her biological parents?", textChinese: "孩子正跟亲生父母一起居住吗？", textKorean: "아동이 친부모와 함께 살고 있습니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "family_history" },
  { id: "living_with_bio_parents_explain", text: "If no, please explain", textChinese: "若不，请注明", textKorean: "아니오인 경우, 설명해 주세요", type: "textarea", domain: "family_history", conditionalOn: "living_with_bio_parents", conditionalValue: "No" },
  { id: "has_babysitter", text: "Does the child have a babysitter / ayah / maid?", textChinese: "有保姆或看护？", textKorean: "아동에게 보모/도우미가 있습니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "family_history" },
  { id: "is_adopted", text: "Is the child adopted?", textChinese: "孩子是否被领养的？", textKorean: "아동이 입양되었습니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "family_history" },
  { id: "adoption_age", text: "Child's age at adoption", textChinese: "孩子被领养时的年龄", textKorean: "입양 시 아동 나이", type: "text", domain: "family_history", conditionalOn: "is_adopted", conditionalValue: "Yes" },
  { id: "parents_divorced", text: "Are the child's parents divorced or separated?", textChinese: "孩子的父母有离异？", textKorean: "부모가 이혼 또는 별거 중입니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "family_history" },
  { id: "custody", text: "Who has custody?", textChinese: "孩子的监护人是", textKorean: "양육권은 누가 가지고 있습니까?", type: "text", domain: "family_history", conditionalOn: "parents_divorced", conditionalValue: "Yes" },
  { id: "parents_remarried", text: "Are the child's parents remarried?", textChinese: "孩子的父母再婚？", textKorean: "부모가 재혼했습니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "family_history" },
  { id: "remarriage_child_age", text: "Child's age at parent's remarriage", textChinese: "再婚时孩子年龄是", textKorean: "부모 재혼 시 아동 나이", type: "text", domain: "family_history", conditionalOn: "parents_remarried", conditionalValue: "Yes" },
  { id: "visitation_rights", text: "If applicable, please describe visitation rights", textChinese: "若适用，请描述孩子的探视权和相关情况", textKorean: "해당하는 경우, 방문권을 설명해 주세요", type: "textarea", domain: "family_history" },
  { id: "primary_caregiver", text: "Who is the child's primary caregiver?", textChinese: "主要照顾孩子的人", textKorean: "아동의 주 양육자는 누구입니까?", type: "text", domain: "family_history" },
  { id: "sibling_relationship", text: "Describe child's relationship with siblings", textChinese: "请描述孩子与兄弟姊妹的关系及相处", textKorean: "형제/자매와의 관계를 설명해 주세요", type: "textarea", domain: "family_history" },
  { id: "discipline_admin", text: "Which parent is more responsible for administering discipline in the home?", textChinese: "父母间，哪方更多地执行家中的纪律？", textKorean: "가정 내 훈육을 더 많이 담당하는 부모는 누구입니까?", type: "text", domain: "family_history" },
  { id: "discipline_style", text: "How would you describe the discipline in the home? Any areas of difficulty?", textChinese: "请仔细形容家中的纪律。如有特别难处，请详述", textKorean: "가정 내 훈육 방식을 설명해 주세요. 어려운 점이 있습니까?", type: "textarea", domain: "family_history" },
  { id: "home_languages", text: "Languages spoken at home", textChinese: "在家沟通的语言", textKorean: "가정에서 사용하는 언어", type: "text", domain: "family_history" },
  { id: "residence_history", text: "Where has the child lived? (Locations and approximate dates)", textChinese: "孩子过往的居住地", textKorean: "아동이 거주한 곳은 어디입니까? (장소 및 대략적인 날짜)", type: "textarea", domain: "family_history" },

  // Family Mental Health
  {
    id: "section_family_mh",
    text: "Family Mental Health History",
    textChinese: "家族心理病历",
    textKorean: "가족 정신건강 병력",
    type: "section_header",
    domain: "family_mh",
    note: "Suspected / Confirmed conditions in the family",
    noteChinese: "家族中有否如下疑似或确诊病症？",
    noteKorean: "가족 중 의심 또는 확진된 병력이 있습니까?",
  },
  { id: "family_mh_learning", text: "Learning Difficulties — Family member and status", textChinese: "学习困难症", textKorean: "학습 장애 — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },
  { id: "family_mh_depression", text: "Depression — Family member and status", textChinese: "抑郁症", textKorean: "우울증 — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },
  { id: "family_mh_anxiety", text: "Anxiety — Family member and status", textChinese: "焦虑症", textKorean: "불안 장애 — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },
  { id: "family_mh_adhd", text: "ADHD — Family member and status", textChinese: "注意力不足多动症", textKorean: "ADHD — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },
  { id: "family_mh_epilepsy", text: "Epilepsy — Family member and status", textChinese: "癫痫症", textKorean: "간질 — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },
  { id: "family_mh_autism", text: "Autism — Family member and status", textChinese: "自闭症", textKorean: "자폐증 — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },
  { id: "family_mh_speech", text: "Speech Difficulty — Family member and status", textChinese: "语言障碍", textKorean: "언어 장애 — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },
  { id: "family_mh_seizures", text: "Seizures — Family member and status", textChinese: "发作", textKorean: "발작 — 가족 구성원 및 현황", type: "textarea", domain: "family_mh" },

  // Academic History
  {
    id: "section_academic",
    text: "Academic History",
    textChinese: "学业历程（请提供过往及现有成绩单）",
    textKorean: "학업 이력 (과거 및 현재 성적표 제출 요망)",
    type: "section_header",
    domain: "academic",
  },
  { id: "current_school", text: "Current School", textChinese: "现时学校", textKorean: "현재 학교", type: "text", domain: "academic" },
  { id: "current_grade", text: "Grade", textChinese: "现时年级", textKorean: "학년", type: "text", domain: "academic" },
  { id: "instruction_language", text: "Language of Instruction at School", textChinese: "教学语言", textKorean: "학교 교육 언어", type: "text", domain: "academic" },
  { id: "school_start_age", text: "Age child started this school", textChinese: "孩子初上学年龄", textKorean: "아동이 이 학교에 입학한 나이", type: "number", domain: "academic" },
  { id: "likes_school", text: "Does the child like school?", textChinese: "孩子喜欢上学吗？", textKorean: "아동이 학교를 좋아합니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "likes_teacher", text: "Does the child like their current teacher?", textChinese: "孩子喜欢现在的老师吗？", textKorean: "아동이 현재 교사를 좋아합니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "enjoys_art", text: "Does the child enjoy art?", textChinese: "孩子喜欢艺术吗？", textKorean: "아동이 미술을 즐깁니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "enjoys_music", text: "Does the child enjoy music?", textChinese: "孩子喜欢音乐吗？", textKorean: "아동이 음악을 즐깁니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "plays_instrument", text: "Does the child play a musical instrument?", textChinese: "孩子会弹奏乐器吗？", textKorean: "아동이 악기를 연주합니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "reads_for_pleasure", text: "Does the child read for pleasure?", textChinese: "孩子在课堂外享受阅读吗？", textKorean: "아동이 즐거움을 위해 독서를 합니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "favorite_subject", text: "Child's favorite subject", textChinese: "孩子最喜爱的科目是", textKorean: "아동이 가장 좋아하는 과목", type: "text", domain: "academic" },
  { id: "special_programming", text: "Does the child receive special programming at school?", textChinese: "孩子在学校接受特别教育吗？", textKorean: "아동이 학교에서 특별 프로그램을 받고 있습니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "special_programming_details", text: "If yes, please specify", textChinese: "若是，请说明", textKorean: "예인 경우, 구체적으로 설명해 주세요", type: "text", domain: "academic", conditionalOn: "special_programming", conditionalValue: "Yes" },
  { id: "has_iep", text: "Does the child have an Individual Education Plan (IEP)?", textChinese: "孩子有「个性化教育计划」吗？", textKorean: "아동에게 개별화 교육 계획(IEP)이 있습니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "iep_details", text: "If yes, please specify", textChinese: "若是，请说明", textKorean: "예인 경우, 구체적으로 설명해 주세요", type: "text", domain: "academic", conditionalOn: "has_iep", conditionalValue: "Yes" },
  { id: "after_school_tutoring", text: "Does the child receive special tutoring after school?", textChinese: "孩子在课后有否接受额外补习吗？", textKorean: "아동이 방과 후 특별 과외를 받고 있습니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "tutoring_details", text: "If yes, please specify", textChinese: "若是，请说明", textKorean: "예인 경우, 구체적으로 설명해 주세요", type: "text", domain: "academic", conditionalOn: "after_school_tutoring", conditionalValue: "Yes" },
  { id: "least_favorite_subject", text: "Child's least favorite subject", textChinese: "孩子最不喜爱的科目是", textKorean: "아동이 가장 싫어하는 과목", type: "text", domain: "academic" },
  {
    id: "academic_difficulties",
    text: "Academic areas the child is currently having difficulty in (check all that apply)",
    textChinese: "请选择孩子目前面对困难的科目（多选）",
    textKorean: "아동이 현재 어려움을 겪고 있는 학업 분야 (해당하는 모든 항목 체크)",
    type: "checkbox_group",
    options: ["Math", "English", "Reading", "Spelling", "Social Studies", "Science", "Foreign language", "Other"],
    optionsChinese: ["数学", "英语", "阅读", "拼写", "社会科学", "科学", "外语", "其他"],
    optionsKorean: ["수학", "영어", "읽기", "철자", "사회", "과학", "외국어", "기타"],
    domain: "academic",
  },
  {
    id: "overall_grades",
    text: "Overall the child's grades are",
    textChinese: "孩子总体大概的学习成绩是",
    textKorean: "아동의 전반적인 성적은",
    type: "radio_group",
    options: ["Below Average", "Average", "Above Average"],
    optionsChinese: ["低于平均", "平均", "高于平均"],
    optionsKorean: ["평균 이하", "평균", "평균 이상"],
    domain: "academic",
    required: true,
  },
  {
    id: "school_problems",
    text: "Indicate which problems, if any, the child has experienced at school",
    textChinese: "请勾选孩子曾在学校中做过或表现过的行为",
    textKorean: "아동이 학교에서 경험한 문제를 표시해 주세요",
    type: "checkbox_group",
    options: [
      "Does not do homework", "Fails to check homework", "Starts but does not finish homework",
      "Does not remain seated", "Incomplete classroom work", "Forgets assignments",
      "Takes excessive time to complete assignments", "Makes many careless errors",
      "Talks out inappropriately in class", "Problems with written language", "Poor Math",
      "Poor spelling", "Poor handwriting", "Poor reading skills", "Messy / Disorganized",
      "Distracted", "Poor attention in class", "Non-Compliant in class", "Test anxiety",
      "Lacks friends",
    ],
    optionsChinese: [
      "不做作业", "不检查课业", "难完成已开始做的课业",
      "难以好好坐下", "不完成课堂内的功课", "忘记课业",
      "需要过长的时间去完成课业", "常犯粗心大意的错",
      "课内随便大声喧哗", "书写文字有困难", "数学成绩弱",
      "拼写能力弱", "字迹不工整", "阅读能力弱", "乱扔东西，欠整洁",
      "容易分心", "上课欠专注", "不遵守课堂秩序及不听讲老师指示", "考试前感焦虑",
      "缺乏朋友",
    ],
    optionsKorean: [
      "숙제를 하지 않음", "숙제 확인을 하지 않음", "시작했지만 완료하지 않음",
      "착석이 어려움", "수업 과제를 완성하지 않음", "과제를 잊어버림",
      "과제 완성에 과도한 시간 소요", "부주의한 실수가 많음",
      "수업 중 부적절한 발언", "서면 언어 문제", "수학 성적 부진",
      "철자 실력 부진", "필체 불량", "읽기 능력 부진", "지저분하고 무질서",
      "산만함", "수업 중 주의력 부족", "수업 규칙 미준수", "시험 불안",
      "친구가 없음",
    ],
    domain: "academic",
  },
  { id: "gets_along_peers", text: "Does the child get along well with peers?", textChinese: "孩子与同龄人关系好吗？", textKorean: "아동이 또래와 잘 어울립니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  { id: "social_interest", text: "Does the child show interest in social interaction?", textChinese: "孩子喜欢与人交际？", textKorean: "아동이 사회적 교류에 관심을 보입니까?", type: "radio_group", options: ["Yes", "No"], optionsKorean: ["예", "아니오"], domain: "academic" },
  {
    id: "peer_interaction_style",
    text: "Interaction with peers, have you noticed that the child is",
    textChinese: "当孩子与朋辈交往时，他表现得",
    textKorean: "또래와의 상호작용에서 아동이 다음과 같다고 느끼신 적이 있습니까?",
    type: "radio_group",
    options: ["Mean / Aggressive", "Shy / Timid", "Bossy / Controlling", "Takes excessive risks"],
    optionsChinese: ["刻薄/好斗", "害羞/胆怯", "专制/霸道", "过份冒险"],
    optionsKorean: ["못되거나 공격적", "수줍음/소심", "권위적/통제적", "과도한 위험 감수"],
    domain: "academic",
  },
  { id: "hobbies", text: "Child's outside hobbies, interests, and/or sports of choice", textChinese: "孩子在校外有什么兴趣、嗜好？他喜欢那类运动？", textKorean: "아동의 과외 취미, 관심사 및/또는 선호하는 스포츠", type: "textarea", domain: "academic" },

  // Health History
  {
    id: "section_health",
    text: "Mental / Physical Health History",
    textChinese: "个人健康历史（请提供所有有关的健康报告）",
    textKorean: "정신/신체 건강 병력 (관련 건강 보고서 모두 제출 요망)",
    type: "section_header",
    domain: "health",
  },
  { id: "prior_evaluations", text: "Prior Evaluations (type, date, location)", textChinese: "请列出孩子曾接受过的检查报告（听力、言语、智力、发育等）", textKorean: "이전 평가 (유형, 날짜, 장소)", type: "textarea", domain: "health" },
  { id: "evaluation_followup", text: "What actions were taken following these evaluations?", textChinese: "评估后的采取措施", textKorean: "이러한 평가 후 어떤 조치가 취해졌습니까?", type: "textarea", domain: "health" },
  {
    id: "problem_frequency",
    text: "How often and in what settings does the problem occur?",
    textChinese: "困难发生的地方与频率",
    textKorean: "문제는 얼마나 자주, 어떤 환경에서 발생합니까?",
    type: "checkbox_group",
    options: [
      "Home — Always", "Home — Often", "Home — Sometimes", "Home — Never",
      "School — Always", "School — Often", "School — Sometimes", "School — Never",
      "With Siblings — Always", "With Siblings — Often", "With Siblings — Sometimes", "With Siblings — Never",
      "With Peers — Always", "With Peers — Often", "With Peers — Sometimes", "With Peers — Never",
      "With Parents — Always", "With Parents — Often", "With Parents — Sometimes", "With Parents — Never",
    ],
    optionsChinese: [
      "在家 — 总是", "在家 — 经常", "在家 — 有时", "在家 — 从不",
      "在校 — 总是", "在校 — 经常", "在校 — 有时", "在校 — 从不",
      "与兄弟姐妹 — 总是", "与兄弟姐妹 — 经常", "与兄弟姐妹 — 有时", "与兄弟姐妹 — 从不",
      "与同龄人 — 总是", "与同龄人 — 经常", "与同龄人 — 有时", "与同龄人 — 从不",
      "与父母 — 总是", "与父母 — 经常", "与父母 — 有时", "与父母 — 从不",
    ],
    optionsKorean: [
      "가정에서 — 항상", "가정에서 — 자주", "가정에서 — 때때로", "가정에서 — 전혀 없음",
      "학교에서 — 항상", "학교에서 — 자주", "학교에서 — 때때로", "학교에서 — 전혀 없음",
      "형제/자매와 — 항상", "형제/자매와 — 자주", "형제/자매와 — 때때로", "형제/자매와 — 전혀 없음",
      "또래와 — 항상", "또래와 — 자주", "또래와 — 때때로", "또래와 — 전혀 없음",
      "부모와 — 항상", "부모와 — 자주", "부모와 — 때때로", "부모와 — 전혀 없음",
    ],
    domain: "health",
  },
  { id: "serious_injury", text: "Serious injury or chronic illness (condition, date, outcome)", textChinese: "请列出孩子过去曾受过的创伤及曾患过的慢性病（包括发高烧）", textKorean: "심각한 부상 또는 만성 질환 (상태, 날짜, 결과)", type: "textarea", domain: "health" },
  { id: "hospitalizations", text: "Hospitalizations (condition, date, length of stay, outcome)", textChinese: "请列出孩子过去曾住院的纪录（包括发高烧）", textKorean: "입원 기록 (상태, 날짜, 입원 기간, 결과)", type: "textarea", domain: "health" },
  { id: "psychiatric_medications", text: "Current psychiatric medications (condition, medication, dosage)", textChinese: "请列出孩子正在服用的精神科药物", textKorean: "현재 복용 중인 정신과 약물 (상태, 약물명, 용량)", type: "textarea", domain: "health" },
  { id: "other_medications", text: "Other current medications (condition, medication, dosage)", textChinese: "请列出孩子正在服用的其他药物", textKorean: "기타 현재 복용 중인 약물 (상태, 약물명, 용량)", type: "textarea", domain: "health" },
  {
    id: "eating_habits",
    text: "Child's eating habits",
    textChinese: "孩子的饮食习惯",
    textKorean: "아동의 식습관",
    type: "radio_group",
    options: ["Under eats", "Eats Normally", "Overeats"],
    optionsChinese: ["比正常少", "正常", "比正常多"],
    optionsKorean: ["적게 먹음", "정상적으로 먹음", "과식"],
    domain: "health",
  },
  {
    id: "sleep_problems",
    text: "Sleep problems (check all that apply)",
    textChinese: "请选择孩子表现以下的睡眠问题（多选）",
    textKorean: "수면 문제 (해당하는 모든 항목 체크)",
    type: "checkbox_group",
    options: [
      "Sleeps less than usual", "Has problems waking up", "Wakes up early in the morning",
      "Wets bed", "Snores", "Wakes up at night", "Mouth-breathes",
      "Has problems falling asleep", "Has nightmares", "Sleeps more than usual",
    ],
    optionsChinese: [
      "睡眠不足", "难以起床", "很早起床",
      "尿床", "打鼻鼾", "半夜醒起", "睡时以嘴巴呼吸",
      "难以入睡", "做噩梦", "睡眠过多",
    ],
    optionsKorean: [
      "평소보다 덜 잠", "일어나는 데 어려움", "이른 아침에 깸",
      "야뇨증", "코골기", "밤에 깸", "구강 호흡",
      "잠들기 어려움", "악몽", "평소보다 많이 잠",
    ],
    domain: "health",
  },
  { id: "additional_notes", text: "Please use the space below to discuss any topic you feel is important that has not yet been covered", textChinese: "请在此写下其他此表格并没提及的重要事项", textKorean: "아직 다루지 않은 중요한 사항이 있다면 아래에 기재해 주세요", type: "textarea", domain: "health" },
];

// ─── EXISTING SCREENER QUESTIONS ────────────────────────────────────────────────
export const SAMPLE_QUESTIONS: Record<string, FormQuestion[]> = {
  default: [
    { id: "q1", text: "Has difficulty sustaining attention in tasks or play activities", textChinese: "在任务或游戏活动中难以持续注意力", textKorean: "과제나 놀이 활동에서 주의를 지속하기 어려움", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "attention" },
    { id: "q2", text: "Often loses things necessary for tasks", textChinese: "经常遗失任务所需的物品", textKorean: "과제에 필요한 물건을 자주 잃어버림", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "attention" },
    { id: "q3", text: "Is easily distracted by extraneous stimuli", textChinese: "容易被无关刺激分心", textKorean: "외부 자극에 쉽게 산만해짐", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "attention" },
    { id: "q4", text: "Has difficulty organizing tasks and activities", textChinese: "难以组织任务和活动", textKorean: "과제와 활동을 체계적으로 정리하기 어려움", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "executive_function" },
    { id: "q5", text: "Has trouble following through on instructions", textChinese: "难以按指示完成工作", textKorean: "지시에 따라 완수하기 어려움", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "executive_function" },
    { id: "q6", text: "Has difficulty regulating emotions", textChinese: "难以调节情绪", textKorean: "감정 조절이 어려움", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "emotional_regulation" },
    { id: "q7", text: "Struggles with transitions between activities", textChinese: "在活动转换时有困难", textKorean: "활동 전환에 어려움을 겪음", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "emotional_regulation" },
    { id: "q8", text: "Has difficulty in social interactions with peers", textChinese: "与同伴的社交互动有困难", textKorean: "또래와의 사회적 상호작용에 어려움이 있음", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "social_communication" },
    { id: "q9", text: "Shows academic persistence when tasks are challenging", textChinese: "面对挑战性任务时表现出学业坚持", textKorean: "도전적인 과제 수행 시 학업 지속성을 보임", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "academic_persistence" },
    { id: "q10", text: "Overall, how would you rate this student's functioning at school?", textChinese: "总体而言，您如何评价这位学生在学校的表现？", textKorean: "전반적으로 이 학생의 학교 생활 기능을 어떻게 평가하시겠습니까?", type: "scale", domain: "general" },
  ],
  "RCS-80": [
    { id: "r1", text: "Inattentive during lessons", textChinese: "课堂上注意力不集中", textKorean: "수업 중 부주의", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "attention" },
    { id: "r2", text: "Difficulty completing homework independently", textChinese: "难以独立完成家庭作业", textKorean: "독립적으로 숙제를 완료하기 어려움", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "executive_function" },
    { id: "r3", text: "Interrupts others frequently", textChinese: "经常打断他人", textKorean: "타인을 자주 방해함", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "social_communication" },
    { id: "r4", text: "Loses temper easily", textChinese: "容易发脾气", textKorean: "쉽게 화를 냄", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "emotional_regulation" },
    { id: "r5", text: "Has difficulty sitting still", textChinese: "难以静坐", textKorean: "가만히 앉아 있기 어려움", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "attention" },
    { id: "r6", text: "Makes careless errors in schoolwork", textChinese: "在学业工作中犯粗心错误", textKorean: "학업에서 부주의한 실수를 저지름", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "attention" },
    { id: "r7", text: "Struggles to wait for turn", textChinese: "难以等待轮到自己", textKorean: "차례를 기다리기 어려움", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "executive_function" },
    { id: "r8", text: "Has problems with reading comprehension", textChinese: "阅读理解有问题", textKorean: "읽기 이해에 어려움이 있음", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, optionsKorean: LIKERT_OPTIONS_KO, domain: "academic_persistence" },
  ],
  REFERRAL: REFERRAL_FORM,
  CONSENT: CONSENT_FORM,
  INTAKE: INTAKE_FORM,
};
