export interface FormQuestion {
  id: string;
  text: string;
  textChinese?: string;
  type: "likert" | "yes_no" | "text" | "textarea" | "scale" | "checkbox_group" | "select" | "date" | "signature" | "radio_group" | "section_header" | "number" | "frequency_grid";
  options?: string[];
  optionsChinese?: string[];
  rows?: FormQuestion[]; // for frequency_grid
  domain: string;
  required?: boolean;
  conditionalOn?: string; // question id
  conditionalValue?: string;
  note?: string;
  noteChinese?: string;
}

const LIKERT_OPTIONS = ["Never", "Rarely", "Sometimes", "Often", "Very Often"];
const LIKERT_OPTIONS_ZH = ["从不", "很少", "有时", "经常", "非常频繁"];

// ─── REFERRAL FORM ─────────────────────────────────────────────────────────────
export const REFERRAL_FORM: FormQuestion[] = [
  {
    id: "referrer_type",
    text: "I am a...",
    textChinese: "我是一个...",
    type: "radio_group",
    options: ["Parent", "School Personnel", "Not a network school"],
    optionsChinese: ["家长", "学校工作人员", "未经认可的教育学校"],
    domain: "referrer",
    required: true,
  },
  {
    id: "school_name",
    text: "ReMynd™ Network School Name",
    textChinese: "ReMynd™ 认证学校名称",
    type: "select",
    options: [
      "Malvern College Chengdu",
      "Chengdu Montpellier International School (MIS)",
      "BASIS International & Bilingual School Chengdu",
      "QSI Chengdu",
      "QSI International School of Haiphong",
      "CDIS Chengdu",
      "CDUT Chengdu",
      "Chengdu Seventh Middle School — International Department",
      "Chengdu Shude Middle / High School — International Department",
      "Chengdu Foreign Languages School – International Division",
      "Dibang Kensi School, Chengdu",
      "SPGS International School Chengdu",
      "Leman International School Chengdu",
      "ISA Guangzhou",
      "Cloud 9 Kindergarten Chengdu",
      "BIBS Chengdu",
      "Dipont KCS Chengdu (King's College School, Chengdu)",
      "Westminster School Chengdu",
      "Chengdu Ottawa Public International School",
      "Qingdao Amerasia International School",
      "Sheko International School",
      "ISNSZ Shenzhen",
      "Achieve Xiamen International School",
      "Foshan EtonHouse International School",
      "NanJing EtonHouse International School",
      "Suzhou EtonHouse International School",
      "Changchun American International School",
      "Jinan Thomas International School",
      "Boren Sino Canadian School",
      "Beijing Huijia Private school",
      "Mountain Kingston Bilingual School",
      "EatonHouse Suzhou",
      "Nanjing International School",
      "Other / Not a network school",
    ],
    domain: "school",
    required: true,
  },
  {
    id: "student_english_name",
    text: "Student's English Name (Optional)",
    textChinese: "学生英文姓名 (可选)",
    type: "text",
    domain: "student",
  },
  {
    id: "student_chinese_first",
    text: "Student's Chinese First Name (Pinyin)",
    textChinese: "学生的中文名字",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_chinese_family",
    text: "Student's Chinese Family Name (Pinyin)",
    textChinese: "学生的中国姓",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "parent_name",
    text: "Parent's Name (Pinyin)",
    textChinese: "父母的名字",
    type: "text",
    domain: "parent",
    required: true,
  },
  {
    id: "parent_email",
    text: "Parent's Email",
    textChinese: "家长邮箱",
    type: "text",
    domain: "parent",
    required: true,
  },
  {
    id: "wechat",
    text: "WeChat",
    textChinese: "微信",
    type: "text",
    domain: "parent",
    required: true,
  },
  {
    id: "student_grade",
    text: "Student's Homeroom / Class",
    textChinese: "学生班级",
    type: "select",
    options: ["K", "G1", "G2", "G3", "G4", "G5", "G6", "G7", "G8", "G9", "G10", "G11", "G12"],
    domain: "student",
    required: true,
  },
  {
    id: "student_age",
    text: "Student's Age",
    textChinese: "学生的年龄",
    type: "number",
    domain: "student",
    required: true,
  },
  {
    id: "student_dob",
    text: "Student's Date of Birth",
    textChinese: "学生出生日期",
    type: "date",
    domain: "student",
    required: true,
  },
  {
    id: "today_date",
    text: "Today's Date",
    textChinese: "今日日期",
    type: "date",
    domain: "referral",
    required: true,
  },
  {
    id: "behavior_locations",
    text: "Where do these behaviors usually take place?",
    textChinese: "这些行为通常发生在哪里?",
    type: "checkbox_group",
    options: [
      "During Classroom Time",
      "Morning Break",
      "Lunchtime",
      "Afternoon Break",
      "During ASA",
      "In Boarding",
      "On School Bus",
      "On a Field Trip",
      "At Camp",
      "Not Applicable",
    ],
    optionsChinese: [
      "课堂时间",
      "上午休息时间",
      "午餐时间",
      "下午休息时间",
      "课外课时间",
      "在宿舍时间",
      "在校车时间",
      "实地考察旅行期间",
      "在露营期间",
      "不适用",
    ],
    domain: "referral",
  },
  {
    id: "teacher1_name",
    text: "Teacher 1 Name (English or Pinyin)",
    textChinese: "老师1名",
    type: "text",
    domain: "teachers",
    required: true,
  },
  {
    id: "teacher1_email",
    text: "Teacher 1 Email",
    textChinese: "电子邮件",
    type: "text",
    domain: "teachers",
    required: true,
  },
  {
    id: "teacher2_name",
    text: "Teacher 2 Name (English or Pinyin)",
    textChinese: "老师2名",
    type: "text",
    domain: "teachers",
  },
  {
    id: "teacher2_email",
    text: "Teacher 2 Email",
    textChinese: "老师2电子邮件",
    type: "text",
    domain: "teachers",
  },
  {
    id: "teacher3_name",
    text: "Teacher 3 Name (English or Pinyin)",
    textChinese: "老师3名",
    type: "text",
    domain: "teachers",
  },
  {
    id: "teacher3_email",
    text: "Teacher 3 Email",
    textChinese: "老师3电子邮件",
    type: "text",
    domain: "teachers",
  },
  {
    id: "details",
    text: "Please give details including any dates of occurrence",
    textChinese: "请提供详细信息，包括任何发生的日期",
    type: "textarea",
    domain: "referral",
  },
  {
    id: "student_history",
    text: "Student Details (Check all that apply)",
    textChinese: "学生详细信息 (检查所有适用的内容)",
    type: "checkbox_group",
    options: [
      "The student has been referred for counselling before",
      "The student is currently seeing a mental health professional",
      "The student is currently on medication",
    ],
    optionsChinese: [
      "这名学生以前曾被转介咨询过",
      "该学生目前正在看心理健康专家",
      "这名学生目前正在服药",
    ],
    domain: "referral",
  },
  {
    id: "actions_taken",
    text: "Actions Already Taken",
    textChinese: "已采取的行动",
    type: "checkbox_group",
    options: [
      "Discussed with Student",
      "Made note in Student Diary / Contacted Parents",
      "Consulted Home Room / Subject Teacher",
      "Consulted Assistant Principal",
      "Consulted EAL Coordinator",
      "Implemented EAL Strategies",
      "Implemented Behavior Management Strategies",
      "Implemented Differentiation Strategies",
      "Consulted School Counselor / Pastoral Care",
      "Consulted Learning Enhancement Staff",
      "Consulted School Nurse",
      "Logged into Managebac",
      "Other",
    ],
    optionsChinese: [
      "和学生进行了交流",
      "在学生的家校交流本上做了记录/联系了父母",
      "咨询家庭室/学科老师",
      "和校长助理进行了沟通",
      "和EAL协调员进行了沟通",
      "采取了EAL的策略",
      "采取了行为管理策略",
      "采取了因材施教策略",
      "咨询学校辅导员",
      "与学习促进老师进行了沟通",
      "与校医进行了沟通",
      "Managebac已登陆",
      "其他",
    ],
    domain: "referral",
    required: true,
  },
  {
    id: "reason_for_referral",
    text: "Reason for Referral",
    textChinese: "推荐的理由",
    type: "checkbox_group",
    options: [
      "School adjustment",
      "Gifted / Grade acceleration",
      "Motivation",
      "Learning difficulties",
      "Disruptive behavior",
      "School refusal",
      "Anxiety",
      "Depression",
      "Low self-esteem",
      "Personal care",
      "Academic progress",
      "Time management",
      "Aggression",
      "Bullying",
      "Anger",
      "Social skills",
      "Poor peer relationships",
      "Home problems",
      "Withdrawn",
      "Stealing",
      "Perfectionist",
      "Fearful",
      "Obscene language",
      "Substance abuse",
      "Self-Harm",
      "Other",
    ],
    optionsChinese: [
      "学校调整",
      "天赋/年级加速度",
      "动机",
      "学习困难",
      "破坏性行为",
      "学校拒绝",
      "焦虑",
      "抑郁症",
      "低自尊",
      "个人护理",
      "学术的进步",
      "时间管理",
      "侵略",
      "欺凌",
      "愤怒",
      "社会技能",
      "同伴关系差",
      "家里的问题",
      "撤销",
      "偷",
      "完美主义者",
      "恐惧",
      "淫秽语言",
      "物质滥用",
      "自残",
      "其他",
    ],
    domain: "referral",
    required: true,
  },
  {
    id: "general_concern_category",
    text: "General Concern Category (Check all that apply)",
    textChinese: "总体类别 (请检查所有适用的)",
    type: "checkbox_group",
    options: [
      "Academic / Learning Support / EAL",
      "Social Skills",
      "Fighting / Bullying",
      "Emotional Support",
      "Family-Related Issues",
      "Crisis Intervention (Urgent)",
      "Other",
    ],
    optionsChinese: [
      "学习方面的支持",
      "社交技能",
      "校园霸陵",
      "情感支持",
      "与家庭因素相关",
      "危机干预（紧急）",
      "其他",
    ],
    domain: "referral",
    required: true,
  },
  {
    id: "additional_comments",
    text: "Additional Comments",
    textChinese: "额外的评论",
    type: "textarea",
    domain: "referral",
  },
];

// ─── CONSENT FORM ──────────────────────────────────────────────────────────────
export const CONSENT_FORM: FormQuestion[] = [
  {
    id: "student_first_name",
    text: "First / Given Name of Student",
    textChinese: "学生姓名",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_last_name",
    text: "Last / Family Name of Student",
    textChinese: "学生姓名（姓）",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_email",
    text: "Email Address of Student",
    textChinese: "学生邮箱",
    type: "text",
    domain: "student",
    required: true,
  },
  {
    id: "student_dob",
    text: "Student's Date of Birth",
    textChinese: "学生出生日期",
    type: "date",
    domain: "student",
    required: true,
  },
  {
    id: "consent_note",
    text: "I am the parent / legal guardian of the above-named student, who wishes to take a student assessment conducted by ReMynd Student Services, and its contracted providers. I understand and acknowledge that all individuals planning to take the assessment are required to agree to all of the terms and conditions contained herein, and that these terms and conditions are legally binding.",
    textChinese: "我是上述学生的父母或监护人，我同意学生参加由ReMynd学生服务及其合作伙伴提供的学生评估。我理解并确认所有计划参加评估的人员均需同意本协议中列出的所有条款和条件，并承认这些条款和条件具有法律约束力。",
    type: "section_header",
    domain: "consent",
  },
  {
    id: "consent_1",
    text: "1. I hereby authorize the above named student to take the assessment; to have all his relevant teachers fill out any necessary forms and questionnaires; to have his school release any relevant past and/or current school records, videos, and work product.",
    textChinese: "1. 我特此授权上述学生参加评估；让他的所有相关教师填写任何必要的表格和问卷；并允许他的学校释放任何相关的过去和/或当前的学校记录、视频和工作成果。",
    type: "radio_group",
    options: ["Yes", "No"],
    domain: "consent",
    required: true,
  },
  {
    id: "consent_2",
    text: "2. I confirm that I completely understand the assessment process as it has been explained to me, including, but not limited to, those provisions relating to testing, privacy policies, the collection, processing, use, and transmission of the student's personally identifiable data (including any digital photographs, signatures, and audio/video recordings collected during testing), and disclosure of such data to ReMynd Student Services, its partners, service providers, any score recipients you select, and others as necessary to prevent unlawful activity or as required by law.",
    textChinese: "2. 我确认我完全理解评估过程，包括但不限于与测试、隐私政策、学生可识别性数据的收集、处理、使用和传输，以及向ReMynd学生服务及其合作伙伴的披露等相关条款。",
    type: "radio_group",
    options: ["Yes", "No"],
    domain: "consent",
    required: true,
  },
  {
    id: "consent_3",
    text: "3. I understand and consent to the use of AI technology, including but not limited to platforms such as Bobby-AI, BastionGPT, and NoteZap, to assist in summarizing information and making written documentation more accessible to families. I acknowledge that the results generated by these AI platforms will be thoroughly vetted and edited for accuracy. I understand that while all companies handling our protected health information are HIPAA-compliant or have signed a business associate agreement (BAA) to ensure confidentiality, there is always a small risk when data is exchanged that confidential information could be leaked.",
    textChinese: "3. 我理解并同意使用人工智能技术，包括但不限于Bobby-AI、BastionGPT和NoteZap等平台，以协助总结信息并使书面文件对家庭更易于获取。我承认这些人工智能平台生成的结果将经过严格审查和编辑以确保准确性。",
    type: "radio_group",
    options: ["Yes", "No"],
    domain: "consent",
    required: true,
  },
  {
    id: "consent_4",
    text: "4. I consent to, and agree that the above named student will comply with and be bound by, all of the terms and conditions herein.",
    textChinese: "4. 我同意并确认上述提到的学生将遵守并受本条款和条件的约束。",
    type: "radio_group",
    options: ["Yes", "No"],
    domain: "consent",
    required: true,
  },
  {
    id: "guardian_name",
    text: "Name of Parent / Legal Guardian (Signature)",
    textChinese: "监护人姓名（签名）",
    type: "signature",
    note: "By writing your name in this box, you agree and attest to the truthfulness and validity of the information in this consent form and give your consent for the above named student to be assessed.",
    noteChinese: "在此框中填写您的姓名，即表示您同意并证明此同意书中的信息是真实和有效的，並授權進行上述學生的評估。",
    domain: "consent",
    required: true,
  },
  {
    id: "consent_date",
    text: "Date",
    textChinese: "日期",
    type: "date",
    domain: "consent",
    required: true,
  },
];

// ─── INTAKE FORM ───────────────────────────────────────────────────────────────
export const INTAKE_FORM: FormQuestion[] = [
  // Section 1: Basic Info
  {
    id: "section_basic",
    text: "Basic Information",
    textChinese: "基本资料",
    type: "section_header",
    domain: "basic",
    note: "Please provide copies of any prior evaluations and past school reports. IMPORTANT: All forms need to be submitted in time for the FIRST day of assessment.",
    noteChinese: "请您附上孩子曾有的评估报告和孩子过往的学校成绩表，并于心理测量的首天与此表格一同提交。",
  },
  { id: "child_last_name", text: "Child's Last Name", textChinese: "姓", type: "text", domain: "basic", required: true },
  { id: "child_first_name", text: "Child's First Name", textChinese: "名", type: "text", domain: "basic", required: true },
  { id: "child_middle_name", text: "Child's Middle Name", textChinese: "中间名", type: "text", domain: "basic" },
  { id: "child_english_name", text: "Child's English Name", textChinese: "英文名", type: "text", domain: "basic" },
  { id: "dob", text: "Date of Birth", textChinese: "出生日期", type: "date", domain: "basic", required: true },
  { id: "school", text: "School", textChinese: "学校", type: "text", domain: "basic", required: true },
  { id: "home_telephone", text: "Home Telephone", textChinese: "家庭电话", type: "text", domain: "basic", required: true },
  { id: "home_address", text: "Home Address", textChinese: "家庭住址", type: "text", domain: "basic", required: true },
  { id: "other_doctors_medication", text: "Other Doctors / Current Medication", textChinese: "其他医生/目前用药", type: "textarea", domain: "basic" },
  {
    id: "child_lives_with",
    text: "The child lives with",
    textChinese: "同孩子共同生活的人",
    type: "checkbox_group",
    options: ["Both parents", "Mother", "Father", "Other"],
    optionsChinese: ["父母", "母亲", "父亲", "其他人"],
    domain: "basic",
    required: true,
  },
  { id: "child_email", text: "Child's Email Address", textChinese: "孩子电邮", type: "text", domain: "basic" },
  { id: "child_mobile", text: "Child's Mobile Number", textChinese: "孩子电话", type: "text", domain: "basic" },

  // Family Members
  {
    id: "section_family_members",
    text: "Family Members (Siblings)",
    textChinese: "家庭成员（包括兄弟姐妹）",
    type: "section_header",
    domain: "family",
  },
  { id: "sibling1_name", text: "Sibling 1 — Name", textChinese: "成员1 — 名字", type: "text", domain: "family" },
  { id: "sibling1_relationship", text: "Sibling 1 — Relationship", textChinese: "关系", type: "text", domain: "family" },
  { id: "sibling1_age", text: "Sibling 1 — Age", textChinese: "年龄", type: "number", domain: "family" },
  { id: "sibling2_name", text: "Sibling 2 — Name", textChinese: "成员2 — 名字", type: "text", domain: "family" },
  { id: "sibling2_relationship", text: "Sibling 2 — Relationship", textChinese: "关系", type: "text", domain: "family" },
  { id: "sibling2_age", text: "Sibling 2 — Age", textChinese: "年龄", type: "number", domain: "family" },
  { id: "sibling3_name", text: "Sibling 3 — Name", textChinese: "成员3 — 名字", type: "text", domain: "family" },
  { id: "sibling3_relationship", text: "Sibling 3 — Relationship", textChinese: "关系", type: "text", domain: "family" },
  { id: "sibling3_age", text: "Sibling 3 — Age", textChinese: "年龄", type: "number", domain: "family" },

  // Parents
  {
    id: "section_parents",
    text: "Parent / Guardian Information",
    textChinese: "父母/监护人信息",
    type: "section_header",
    domain: "parents",
  },
  { id: "father_name", text: "Name of Father / Stepfather", textChinese: "父亲/继父名字", type: "text", domain: "parents" },
  { id: "father_mobile", text: "Father's Mobile Phone", textChinese: "父亲的手机", type: "text", domain: "parents" },
  { id: "father_email", text: "Father's Email", textChinese: "父亲的电子邮件", type: "text", domain: "parents" },
  { id: "father_address", text: "Father's Home / Work Address", textChinese: "父亲的家庭/工作地址", type: "text", domain: "parents" },
  { id: "father_occupation", text: "Father's Occupation / Employer", textChinese: "父亲的职业/雇主", type: "text", domain: "parents" },
  { id: "mother_name", text: "Name of Mother / Stepmother", textChinese: "母亲/继母名字", type: "text", domain: "parents" },
  { id: "mother_mobile", text: "Mother's Mobile Phone", textChinese: "母亲的手机", type: "text", domain: "parents" },
  { id: "mother_email", text: "Mother's Email", textChinese: "母亲的电子邮件", type: "text", domain: "parents" },
  { id: "mother_address", text: "Mother's Home / Work Address", textChinese: "母亲的家庭/工作地址", type: "text", domain: "parents" },
  { id: "mother_occupation", text: "Mother's Occupation / Employer", textChinese: "母亲的职业/雇主", type: "text", domain: "parents" },

  // Referral Info
  {
    id: "section_referral",
    text: "Referral Information",
    textChinese: "推荐信息",
    type: "section_header",
    domain: "referral",
  },
  { id: "reason_for_testing", text: "Reason for Testing", textChinese: "接受测试原因", type: "textarea", domain: "referral", required: true },
  { id: "referred_by", text: "Referred By (Person / Organization)", textChinese: "推荐人/机构", type: "text", domain: "referral" },
  { id: "previous_diagnosis", text: "Previous Diagnosis", textChinese: "过往诊断", type: "text", domain: "referral" },
  { id: "diagnosis_year", text: "Year of Diagnosis", textChinese: "诊断年份", type: "text", domain: "referral" },
  { id: "diagnosis_by", text: "Diagnosis Given By", textChinese: "诊症医生或机构", type: "text", domain: "referral" },
  { id: "present_issues", text: "Present Issues — List major concerns / reasons for testing in your own words", textChinese: "请仔细描述孩子的现况或困难与主要接受测量的原因", type: "textarea", domain: "referral", required: true },
  { id: "noticed_by_person", text: "When and by whom were these difficulties noticed — Person", textChinese: "何人察觉异状", type: "text", domain: "referral" },
  { id: "noticed_approximate_time", text: "Approximate time difficulties have been present", textChinese: "状况维持的时间", type: "text", domain: "referral" },
  { id: "behavior_effect", text: "What effect does the behavior have on the child and those around them?", textChinese: "这些行为如何影响孩子及其身边的人？", type: "textarea", domain: "referral" },

  // Behavioral Checklist
  {
    id: "section_behavior",
    text: "Behavioral Checklist — Check any that apply",
    textChinese: "请选择符合孩子情况的描述（多选）",
    type: "section_header",
    domain: "behavior",
  },
  {
    id: "behavioral_checklist",
    text: "Behavioral Characteristics",
    textChinese: "行为特征",
    type: "checkbox_group",
    options: [
      "Cries easily", "Shy", "Disobedient", "Easily distracted", "Misbehaves at school",
      "Hurts others", "Seems Happy", "Complains about homework", "Affectionate",
      "Seems Immature for age", "Follows Instructions", "Polite", "Difficult",
      "Dislikes handwriting", "Fidgets", "Seems sad", "Finds Transitions Difficult",
      "Makes poor eye contact", "Has difficulty sustaining effort", "Loses personal items",
      "Procrastinates", "Popular", "Interrupts others", "Overly Sensitive", "Quick to Anger",
      "Tells Lies", "Disorganized", "Learns quickly", "Wets bed", "Complains about school",
      "Seeks Attention", "Overactive", "Stubborn", "Nurturing to younger kids", "Anxious",
      "Volatile", "Easily frustrated", "Outgoing", "Steals", "Misbehaves at home",
      "Argumentative", "Cooperative", "Has nightmares", "Overly dramatic",
      "Throws temper tantrums", "Bossy", "Eager to Please",
    ],
    optionsChinese: [
      "易哭", "害羞", "悖逆", "容易分神", "在校内不守纪律",
      "伤害别人", "看起来开心", "抱怨课业", "有丰富感情",
      "较同龄孩子不成熟", "听从指示", "有礼貌", "难以亲近",
      "不爱书写", "烦躁不安", "看起来忧伤", "适应力差",
      "说话时欠缺眼神接触", "欠缺恒心", "丢三落四",
      "爱拖延耽搁", "受欢迎", "打扰别人", "过于敏感", "容易动怒",
      "说谎", "做事欠条理", "学习速度快", "尿床", "抱怨学校",
      "爱引人注意", "过度活跃", "固执", "关心比自己小的孩童", "易焦虑",
      "善变", "容易沮丧", "外向好动", "有偷窃行为", "在家不守规矩",
      "喜好争辩", "乐于合作", "造噩梦", "戏剧性及浮夸行为",
      "乱发脾气", "专横", "渴望取悦他人",
    ],
    domain: "behavior",
  },
  { id: "strengths", text: "What are the child's strengths and positive qualities? What are they good at?", textChinese: "孩子有什么强项及优点？在学校、在家中、交际上、艺术上擅长之处是什么？", type: "textarea", domain: "behavior" },

  // Developmental History
  {
    id: "section_developmental",
    text: "Developmental History",
    textChinese: "成长及发育历程",
    type: "section_header",
    domain: "developmental",
  },
  { id: "mother_age_at_birth", text: "Mother's Age at Child's Birth", textChinese: "母亲产子年龄", type: "number", domain: "developmental", required: true },
  { id: "father_age_at_birth", text: "Father's Age at Child's Birth", textChinese: "父亲在孩子出生时的年龄", type: "number", domain: "developmental" },
  { id: "pregnancy_length", text: "Length of Pregnancy", textChinese: "怀孕时间长短", type: "text", domain: "developmental" },
  { id: "birth_weight", text: "Birth Weight", textChinese: "孩子出生体重", type: "text", domain: "developmental" },
  { id: "condition_at_birth", text: "Condition at Birth", textChinese: "孩子出生状况", type: "text", domain: "developmental" },
  { id: "pregnancy_complications", text: "Were there any complications during pregnancy?", textChinese: "怀孕时的特别症状或并发症", type: "textarea", domain: "developmental" },
  { id: "delivery_complications", text: "Were there any complications during delivery?", textChinese: "产子时的特别症状或并发症", type: "textarea", domain: "developmental", required: true },
  {
    id: "anesthesia",
    text: "Anesthesia during childbirth",
    textChinese: "产子时的麻醉情况",
    type: "radio_group",
    options: ["None", "Local", "Epidural", "General"],
    optionsChinese: ["无麻醉", "局部麻醉", "无痛分娩", "全身麻醉"],
    domain: "developmental",
    required: true,
  },
  {
    id: "delivery_method",
    text: "Method of Delivery",
    textChinese: "产子方式",
    type: "radio_group",
    options: ["Natural", "Forceps", "Ventous Suction", "Caesarian Section"],
    optionsChinese: ["自然分娩", "产钳分娩", "吸道分娩", "剖腹分娩"],
    domain: "developmental",
    required: true,
  },
  {
    id: "birth_problems",
    text: "Were any of the following problems present at birth?",
    textChinese: "有否发生以下状况？",
    type: "checkbox_group",
    options: ["Breathing problems", "Cord around the neck", "Unusual color", "Problems feeding", "Problems sleeping"],
    optionsChinese: ["呼吸困难", "脐带缠颈", "脸色异常", "哺喂困难", "睡眠困难"],
    domain: "developmental",
  },
  {
    id: "motor_development",
    text: "Motor Development",
    textChinese: "行动发育",
    type: "radio_group",
    options: ["Delayed", "Typical", "Fast"],
    optionsChinese: ["迟缓", "正常", "较快"],
    domain: "developmental",
  },
  {
    id: "speech_development",
    text: "Speech and Linguistic Development",
    textChinese: "语言表达及说话能力发展",
    type: "radio_group",
    options: ["Delayed", "Typical", "Fast"],
    optionsChinese: ["迟缓", "正常", "较快"],
    domain: "developmental",
  },
  { id: "babble_age", text: "Approximate age when child started to babble", textChinese: "孩子初学会牙牙说话的年龄", type: "text", domain: "developmental" },
  { id: "talk_age", text: "Approximate age when child started to talk", textChinese: "孩子初学会说话的年龄", type: "text", domain: "developmental" },
  {
    id: "self_help",
    text: "Self-help / Self-care Development",
    textChinese: "自理能力发育",
    type: "radio_group",
    options: ["Delayed", "Typical", "Fast"],
    optionsChinese: ["迟缓", "正常", "较快"],
    domain: "developmental",
  },
  { id: "toilet_age", text: "Approximate age when child started to use the toilet", textChinese: "孩子初学会如厕的年龄", type: "text", domain: "developmental" },
  { id: "dress_age", text: "Approximate age when child started to dress themselves", textChinese: "孩子初学会穿衣服的年龄", type: "text", domain: "developmental" },
  {
    id: "infant_temperament",
    text: "Temperament as an infant / toddler (check all that apply)",
    textChinese: "婴孩/幼儿时期的性情（多选）",
    type: "checkbox_group",
    options: [
      "Fearful", "Curious", "Easy to manage", "Always Falling", "More interested in things than people",
      "Shy or Timid", "Into everything", "Alert", "Slow to warm up", "Does not engage in imaginative play",
      "Stubborn", "Affectionate", "Aggressive", "Breaks toys",
      "Plays next to kids rather than playing with them", "Impulsive", "Underactive",
      "Dare-Devil", "Overactive", "Rocking or repetitive motions",
    ],
    optionsChinese: [
      "恐惧", "好奇", "容易照料", "易受他人影响", "对事物比对人更有兴趣",
      "害羞", "对什么事都感兴趣", "警惕", "慢热", "不爱在自我想像中的情形玩乐和游戏",
      "固执", "情感丰富", "好斗", "爱把玩具弄坏",
      "在别的孩子旁玩而不与他们一起玩", "冲动", "过于静态",
      "胆子大", "过于好动", "有重复或摇晃的动作",
    ],
    domain: "developmental",
  },

  // Family History
  {
    id: "section_family_history",
    text: "Family History",
    textChinese: "家庭背景",
    type: "section_header",
    domain: "family_history",
  },
  { id: "home_members", text: "Who lives at home besides the child? (Names and relationships)", textChinese: "家中成员及其关系（如祖父母、佣人、兄弟姊妹等）", type: "textarea", domain: "family_history" },
  { id: "living_with_bio_parents", text: "Is the child living with his/her biological parents?", textChinese: "孩子正跟亲生父母一起居住吗？", type: "radio_group", options: ["Yes", "No"], domain: "family_history" },
  { id: "living_with_bio_parents_explain", text: "If no, please explain", textChinese: "若不，请注明", type: "textarea", domain: "family_history", conditionalOn: "living_with_bio_parents", conditionalValue: "No" },
  { id: "has_babysitter", text: "Does the child have a babysitter / ayah / maid?", textChinese: "有保姆或看护？", type: "radio_group", options: ["Yes", "No"], domain: "family_history" },
  { id: "is_adopted", text: "Is the child adopted?", textChinese: "孩子是否被领养的？", type: "radio_group", options: ["Yes", "No"], domain: "family_history" },
  { id: "adoption_age", text: "Child's age at adoption", textChinese: "孩子被领养时的年龄", type: "text", domain: "family_history", conditionalOn: "is_adopted", conditionalValue: "Yes" },
  { id: "parents_divorced", text: "Are the child's parents divorced or separated?", textChinese: "孩子的父母有离异？", type: "radio_group", options: ["Yes", "No"], domain: "family_history" },
  { id: "custody", text: "Who has custody?", textChinese: "孩子的监护人是", type: "text", domain: "family_history", conditionalOn: "parents_divorced", conditionalValue: "Yes" },
  { id: "parents_remarried", text: "Are the child's parents remarried?", textChinese: "孩子的父母再婚？", type: "radio_group", options: ["Yes", "No"], domain: "family_history" },
  { id: "remarriage_child_age", text: "Child's age at parent's remarriage", textChinese: "再婚时孩子年龄是", type: "text", domain: "family_history", conditionalOn: "parents_remarried", conditionalValue: "Yes" },
  { id: "visitation_rights", text: "If applicable, please describe visitation rights", textChinese: "若适用，请描述孩子的探视权和相关情况", type: "textarea", domain: "family_history" },
  { id: "primary_caregiver", text: "Who is the child's primary caregiver?", textChinese: "主要照顾孩子的人", type: "text", domain: "family_history" },
  { id: "sibling_relationship", text: "Describe child's relationship with siblings", textChinese: "请描述孩子与兄弟姊妹的关系及相处", type: "textarea", domain: "family_history" },
  { id: "discipline_admin", text: "Which parent is more responsible for administering discipline in the home?", textChinese: "父母间，哪方更多地执行家中的纪律？", type: "text", domain: "family_history" },
  { id: "discipline_style", text: "How would you describe the discipline in the home? Any areas of difficulty?", textChinese: "请仔细形容家中的纪律。如有特别难处，请详述", type: "textarea", domain: "family_history" },
  { id: "home_languages", text: "Languages spoken at home", textChinese: "在家沟通的语言", type: "text", domain: "family_history" },
  { id: "residence_history", text: "Where has the child lived? (Locations and approximate dates)", textChinese: "孩子过往的居住地", type: "textarea", domain: "family_history" },

  // Family Mental Health
  {
    id: "section_family_mh",
    text: "Family Mental Health History",
    textChinese: "家族心理病历",
    type: "section_header",
    domain: "family_mh",
    note: "Suspected / Confirmed conditions in the family",
    noteChinese: "家族中有否如下疑似或确诊病症？",
  },
  { id: "family_mh_learning", text: "Learning Difficulties — Family member and status", textChinese: "学习困难症", type: "textarea", domain: "family_mh" },
  { id: "family_mh_depression", text: "Depression — Family member and status", textChinese: "抑郁症", type: "textarea", domain: "family_mh" },
  { id: "family_mh_anxiety", text: "Anxiety — Family member and status", textChinese: "焦虑症", type: "textarea", domain: "family_mh" },
  { id: "family_mh_adhd", text: "ADHD — Family member and status", textChinese: "注意力不足多动症", type: "textarea", domain: "family_mh" },
  { id: "family_mh_epilepsy", text: "Epilepsy — Family member and status", textChinese: "癫痫症", type: "textarea", domain: "family_mh" },
  { id: "family_mh_autism", text: "Autism — Family member and status", textChinese: "自闭症", type: "textarea", domain: "family_mh" },
  { id: "family_mh_speech", text: "Speech Difficulty — Family member and status", textChinese: "语言障碍", type: "textarea", domain: "family_mh" },
  { id: "family_mh_seizures", text: "Seizures — Family member and status", textChinese: "发作", type: "textarea", domain: "family_mh" },

  // Academic History
  {
    id: "section_academic",
    text: "Academic History",
    textChinese: "学业历程（请提供过往及现有成绩单）",
    type: "section_header",
    domain: "academic",
  },
  { id: "current_school", text: "Current School", textChinese: "现时学校", type: "text", domain: "academic" },
  { id: "current_grade", text: "Grade", textChinese: "现时年级", type: "text", domain: "academic" },
  { id: "instruction_language", text: "Language of Instruction at School", textChinese: "教学语言", type: "text", domain: "academic" },
  { id: "school_start_age", text: "Age child started this school", textChinese: "孩子初上学年龄", type: "number", domain: "academic" },
  { id: "likes_school", text: "Does the child like school?", textChinese: "孩子喜欢上学吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "likes_teacher", text: "Does the child like their current teacher?", textChinese: "孩子喜欢现在的老师吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "enjoys_art", text: "Does the child enjoy art?", textChinese: "孩子喜欢艺术吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "enjoys_music", text: "Does the child enjoy music?", textChinese: "孩子喜欢音乐吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "plays_instrument", text: "Does the child play a musical instrument?", textChinese: "孩子会弹奏乐器吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "reads_for_pleasure", text: "Does the child read for pleasure?", textChinese: "孩子在课堂外享受阅读吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "favorite_subject", text: "Child's favorite subject", textChinese: "孩子最喜爱的科目是", type: "text", domain: "academic" },
  { id: "special_programming", text: "Does the child receive special programming at school?", textChinese: "孩子在学校接受特别教育吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "special_programming_details", text: "If yes, please specify", textChinese: "若是，请说明", type: "text", domain: "academic", conditionalOn: "special_programming", conditionalValue: "Yes" },
  { id: "has_iep", text: "Does the child have an Individual Education Plan (IEP)?", textChinese: "孩子有「个性化教育计划」吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "iep_details", text: "If yes, please specify", textChinese: "若是，请说明", type: "text", domain: "academic", conditionalOn: "has_iep", conditionalValue: "Yes" },
  { id: "after_school_tutoring", text: "Does the child receive special tutoring after school?", textChinese: "孩子在课后有否接受额外补习吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "tutoring_details", text: "If yes, please specify", textChinese: "若是，请说明", type: "text", domain: "academic", conditionalOn: "after_school_tutoring", conditionalValue: "Yes" },
  { id: "least_favorite_subject", text: "Child's least favorite subject", textChinese: "孩子最不喜爱的科目是", type: "text", domain: "academic" },
  {
    id: "academic_difficulties",
    text: "Academic areas the child is currently having difficulty in (check all that apply)",
    textChinese: "请选择孩子目前面对困难的科目（多选）",
    type: "checkbox_group",
    options: ["Math", "English", "Reading", "Spelling", "Social Studies", "Science", "Foreign language", "Other"],
    optionsChinese: ["数学", "英语", "阅读", "拼写", "社会科学", "科学", "外语", "其他"],
    domain: "academic",
  },
  {
    id: "overall_grades",
    text: "Overall the child's grades are",
    textChinese: "孩子总体大概的学习成绩是",
    type: "radio_group",
    options: ["Below Average", "Average", "Above Average"],
    optionsChinese: ["低于平均", "平均", "高于平均"],
    domain: "academic",
    required: true,
  },
  {
    id: "school_problems",
    text: "Indicate which problems, if any, the child has experienced at school",
    textChinese: "请勾选孩子曾在学校中做过或表现过的行为",
    type: "checkbox_group",
    options: [
      "Does not do homework", "Fails to check homework", "Starts but does not finish homework",
      "Does not remain seated", "Incomplete classroom work", "Forgets assignments",
      "Takes excessive time to complete assignments", "Makes many careless errors",
      "Talks out inappropriately in class", "Problems with written language", "Poor Math",
      "Poor spelling", "Poor handwriting", "Poor reading skills", "Messy / Disorganized",
      "Distracted", "Poor attention in class", "Non-Compliant in class", "Test anxiety",
      "Lacks friends",
    ],
    optionsChinese: [
      "不做作业", "不检查课业", "难完成已开始做的课业",
      "难以好好坐下", "不完成课堂内的功课", "忘记课业",
      "需要过长的时间去完成课业", "常犯粗心大意的错",
      "课内随便大声喧哗", "书写文字有困难", "数学成绩弱",
      "拼写能力弱", "字迹不工整", "阅读能力弱", "乱扔东西，欠整洁",
      "容易分心", "上课欠专注", "不遵守课堂秩序及不听讲老师指示", "考试前感焦虑",
      "缺乏朋友",
    ],
    domain: "academic",
  },
  { id: "gets_along_peers", text: "Does the child get along well with peers?", textChinese: "孩子与同龄人关系好吗？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  { id: "social_interest", text: "Does the child show interest in social interaction?", textChinese: "孩子喜欢与人交际？", type: "radio_group", options: ["Yes", "No"], domain: "academic" },
  {
    id: "peer_interaction_style",
    text: "Interaction with peers, have you noticed that the child is",
    textChinese: "当孩子与朋辈交往时，他表现得",
    type: "radio_group",
    options: ["Mean / Aggressive", "Shy / Timid", "Bossy / Controlling", "Takes excessive risks"],
    optionsChinese: ["刻薄/好斗", "害羞/胆怯", "专制/霸道", "过份冒险"],
    domain: "academic",
  },
  { id: "hobbies", text: "Child's outside hobbies, interests, and/or sports of choice", textChinese: "孩子在校外有什么兴趣、嗜好？他喜欢那类运动？", type: "textarea", domain: "academic" },

  // Health History
  {
    id: "section_health",
    text: "Mental / Physical Health History",
    textChinese: "个人健康历史（请提供所有有关的健康报告）",
    type: "section_header",
    domain: "health",
  },
  { id: "prior_evaluations", text: "Prior Evaluations (type, date, location)", textChinese: "请列出孩子曾接受过的检查报告（听力、言语、智力、发育等）", type: "textarea", domain: "health" },
  { id: "evaluation_followup", text: "What actions were taken following these evaluations?", textChinese: "评估后的采取措施", type: "textarea", domain: "health" },
  {
    id: "problem_frequency",
    text: "How often and in what settings does the problem occur?",
    textChinese: "困难发生的地方与频率",
    type: "checkbox_group",
    options: [
      "Home — Always", "Home — Often", "Home — Sometimes", "Home — Never",
      "School — Always", "School — Often", "School — Sometimes", "School — Never",
      "With Siblings — Always", "With Siblings — Often", "With Siblings — Sometimes", "With Siblings — Never",
      "With Peers — Always", "With Peers — Often", "With Peers — Sometimes", "With Peers — Never",
      "With Parents — Always", "With Parents — Often", "With Parents — Sometimes", "With Parents — Never",
    ],
    domain: "health",
  },
  { id: "serious_injury", text: "Serious injury or chronic illness (condition, date, outcome)", textChinese: "请列出孩子过去曾受过的创伤及曾患过的慢性病（包括发高烧）", type: "textarea", domain: "health" },
  { id: "hospitalizations", text: "Hospitalizations (condition, date, length of stay, outcome)", textChinese: "请列出孩子过去曾住院的纪录（包括发高烧）", type: "textarea", domain: "health" },
  { id: "psychiatric_medications", text: "Current psychiatric medications (condition, medication, dosage)", textChinese: "请列出孩子正在服用的精神科药物", type: "textarea", domain: "health" },
  { id: "other_medications", text: "Other current medications (condition, medication, dosage)", textChinese: "请列出孩子正在服用的其他药物", type: "textarea", domain: "health" },
  {
    id: "eating_habits",
    text: "Child's eating habits",
    textChinese: "孩子的饮食习惯",
    type: "radio_group",
    options: ["Under eats", "Eats Normally", "Overeats"],
    optionsChinese: ["比正常少", "正常", "比正常多"],
    domain: "health",
  },
  {
    id: "sleep_problems",
    text: "Sleep problems (check all that apply)",
    textChinese: "请选择孩子表现以下的睡眠问题（多选）",
    type: "checkbox_group",
    options: [
      "Sleeps less than usual", "Has problems waking up", "Wakes up early in the morning",
      "Wets bed", "Snores", "Wakes up at night", "Mouth-breathes",
      "Has problems falling asleep", "Has nightmares", "Sleeps more than usual",
    ],
    optionsChinese: [
      "睡眠不足", "难以起床", "很早起床",
      "尿床", "打鼻鼾", "半夜醒起", "睡时以嘴巴呼吸",
      "难以入睡", "做噩梦", "睡眠过多",
    ],
    domain: "health",
  },
  { id: "additional_notes", text: "Please use the space below to discuss any topic you feel is important that has not yet been covered", textChinese: "请在此写下其他此表格并没提及的重要事项", type: "textarea", domain: "health" },
];

// ─── EXISTING SCREENER QUESTIONS ────────────────────────────────────────────────
export const SAMPLE_QUESTIONS: Record<string, FormQuestion[]> = {
  default: [
    { id: "q1", text: "Has difficulty sustaining attention in tasks or play activities", textChinese: "在任务或游戏活动中难以持续注意力", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "attention" },
    { id: "q2", text: "Often loses things necessary for tasks", textChinese: "经常遗失任务所需的物品", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "attention" },
    { id: "q3", text: "Is easily distracted by extraneous stimuli", textChinese: "容易被无关刺激分心", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "attention" },
    { id: "q4", text: "Has difficulty organizing tasks and activities", textChinese: "难以组织任务和活动", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "executive_function" },
    { id: "q5", text: "Has trouble following through on instructions", textChinese: "难以按指示完成工作", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "executive_function" },
    { id: "q6", text: "Has difficulty regulating emotions", textChinese: "难以调节情绪", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "emotional_regulation" },
    { id: "q7", text: "Struggles with transitions between activities", textChinese: "在活动转换时有困难", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "emotional_regulation" },
    { id: "q8", text: "Has difficulty in social interactions with peers", textChinese: "与同伴的社交互动有困难", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "social_communication" },
    { id: "q9", text: "Shows academic persistence when tasks are challenging", textChinese: "面对挑战性任务时表现出学业坚持", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "academic_persistence" },
    { id: "q10", text: "Overall, how would you rate this student's functioning at school?", textChinese: "总体而言，您如何评价这位学生在学校的表现？", type: "scale", domain: "general" },
  ],
  "RCS-80": [
    { id: "r1", text: "Inattentive during lessons", textChinese: "课堂上注意力不集中", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "attention" },
    { id: "r2", text: "Difficulty completing homework independently", textChinese: "难以独立完成家庭作业", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "executive_function" },
    { id: "r3", text: "Interrupts others frequently", textChinese: "经常打断他人", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "social_communication" },
    { id: "r4", text: "Loses temper easily", textChinese: "容易发脾气", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "emotional_regulation" },
    { id: "r5", text: "Has difficulty sitting still", textChinese: "难以静坐", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "attention" },
    { id: "r6", text: "Makes careless errors in schoolwork", textChinese: "在学业工作中犯粗心错误", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "attention" },
    { id: "r7", text: "Struggles to wait for turn", textChinese: "难以等待轮到自己", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "executive_function" },
    { id: "r8", text: "Has problems with reading comprehension", textChinese: "阅读理解有问题", type: "likert", options: LIKERT_OPTIONS, optionsChinese: LIKERT_OPTIONS_ZH, domain: "academic_persistence" },
  ],
  REFERRAL: REFERRAL_FORM,
  CONSENT: CONSENT_FORM,
  INTAKE: INTAKE_FORM,
};
