import { Router, type IRouter } from "express";
import healthRouter from "./health";
import casesRouter from "./cases";
import assessmentToolsRouter from "./assessmentTools";
import assignmentsRouter from "./assignments";
import externalRouter from "./external";
import scoresRouter from "./scores";
import reportsRouter from "./reports";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import batteriesRouter from "./batteries";
import portalRouter from "./portal";
import storageRouter from "./storage";
import reportAccessRouter from "./reportAccess";
import rppiRouter from "./rppi";
import rdaRouter from "./rda";
import rrfaRouter from "./rrfa";
import rrcaRouter from "./rrca";
import remyndIndexRouter from "./remynd-index";
import productsRouter from "./products";
import rmraRouter from "./rmra";
import ramriInterviewRouter from "./ramri-interview";
import raepaRouter from "./raepa";
import apprenticesRouter from "./apprentices";
import interviewRecordingsRouter from "./interviewRecordings";
import { denyApprentice } from "../middlewares/denyApprentice.js";
import { apprenticeGuard } from "../middlewares/apprenticeGuard.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(apprenticesRouter);
router.use(apprenticeGuard, casesRouter);
router.use(apprenticeGuard, assessmentToolsRouter);
router.use(apprenticeGuard, assignmentsRouter);
router.use(externalRouter);
router.use(apprenticeGuard, scoresRouter);
router.use(apprenticeGuard, reportsRouter);
router.use(denyApprentice, dashboardRouter);
router.use(apprenticeGuard, batteriesRouter);
router.use(portalRouter);
router.use(storageRouter);
router.use(apprenticeGuard, reportAccessRouter);
router.use(apprenticeGuard, rppiRouter);
router.use(apprenticeGuard, rdaRouter);
router.use(apprenticeGuard, rrfaRouter);
router.use(apprenticeGuard, rrcaRouter);
router.use(apprenticeGuard, remyndIndexRouter);
router.use(apprenticeGuard, productsRouter);
router.use(apprenticeGuard, rmraRouter);
router.use(apprenticeGuard, ramriInterviewRouter);
router.use(apprenticeGuard, raepaRouter);
router.use(apprenticeGuard, interviewRecordingsRouter);

export default router;
