import { Router, type IRouter } from "express";
import healthRouter from "./health";
import casesRouter from "./cases";
import assessmentToolsRouter from "./assessmentTools";
import assignmentsRouter from "./assignments";
import externalRouter from "./external";
import scoresRouter from "./scores";
import reportsRouter from "./reports";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import batteriesRouter from "./batteries";
import portalRouter from "./portal";
import storageRouter from "./storage";
import reportAccessRouter from "./reportAccess";
import rppiRouter from "./rppi";
import rdaRouter from "./rda";
import rrfaRouter from "./rrfa";
import rrcaRouter from "./rrca";
import remyndIndexRouter from "./remynd-index";
import productsRouter from "./products";
import rmraRouter from "./rmra";
import apprenticesRouter from "./apprentices";
import { denyApprentice } from "../middlewares/denyApprentice.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use(usersRouter);
router.use(apprenticesRouter);
router.use(denyApprentice, casesRouter);
router.use(denyApprentice, assessmentToolsRouter);
router.use(denyApprentice, assignmentsRouter);
router.use(externalRouter);
router.use(denyApprentice, scoresRouter);
router.use(denyApprentice, reportsRouter);
router.use(denyApprentice, dashboardRouter);
router.use(denyApprentice, batteriesRouter);
router.use(portalRouter);
router.use(storageRouter);
router.use(denyApprentice, reportAccessRouter);
router.use(denyApprentice, rppiRouter);
router.use(denyApprentice, rdaRouter);
router.use(denyApprentice, rrfaRouter);
router.use(denyApprentice, rrcaRouter);
router.use(denyApprentice, remyndIndexRouter);
router.use(denyApprentice, productsRouter);
router.use(denyApprentice, rmraRouter);

export default router;
